<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data – Why Statistics?</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/3R_Description.html" rel="next">
<link href="../chapters/1R_WhyStats.html" rel="prev">
<link href=".././images/open_source_mouse.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-97aa707caafbe797ecdc85f6e90b4563.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Why Statistics?</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="http://catterson.github.io/calstats/calstatsSP25.html"> 
<span class="menu-text">Psych 101 [Lecture Notes, Labs, Syllabus]</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../Rcode.html" aria-current="page"> 
<span class="menu-text">List of R Code</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://catterson.github.io"> 
<span class="menu-text">Prof.&nbsp;Cat Homepage</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/1R_WhyStats.html">Describing People</a></li><li class="breadcrumb-item"><a href="../chapters/2R_Data.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="../index.html" class="sidebar-logo-link">
      <img src=".././images/open_source_mouse.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hello!</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Describing People</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/1R_WhyStats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Why Statistics?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/2R_Data.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/3R_Description.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Description</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/4R_Scales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Measures</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/5R_GoodScience.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Why Research Methods?</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Predicting People</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/6R_LinearModels.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">The Linear Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/7R_CategoricalIV.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Linear Model Pt 2: Categorical IVs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/8R_3PlusLevelsExperiments.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">More Levels and Experiments</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Predicting Reality</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/9R_SamplingError.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Sampling Error and Bias</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/10R_MultipleRegression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Multiple Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/11R_InteractionFX.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Interaction Effects</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/12R_Conclusion2Introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Conclusion 2 Introduction</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Rcode.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Rcode</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#part-1-defining-data" id="toc-part-1-defining-data" class="nav-link active" data-scroll-target="#part-1-defining-data">Part 1 : Defining Data</a>
  <ul class="collapse">
  <li><a href="#numeric-variables" id="toc-numeric-variables" class="nav-link" data-scroll-target="#numeric-variables">Numeric variables</a>
  <ul class="collapse">
  <li><a href="#definition-numeric-variable" id="toc-definition-numeric-variable" class="nav-link" data-scroll-target="#definition-numeric-variable">Definition : Numeric Variable</a></li>
  <li><a href="#graphing-the-histogram" id="toc-graphing-the-histogram" class="nav-link" data-scroll-target="#graphing-the-histogram">Graphing : The Histogram</a></li>
  <li><a href="#activity-think-about-data" id="toc-activity-think-about-data" class="nav-link" data-scroll-target="#activity-think-about-data">Activity : Think about Data!</a></li>
  </ul></li>
  <li><a href="#categorical-factor-variable" id="toc-categorical-factor-variable" class="nav-link" data-scroll-target="#categorical-factor-variable">Categorical Factor Variable</a>
  <ul class="collapse">
  <li><a href="#definition-categorical-factor-variable" id="toc-definition-categorical-factor-variable" class="nav-link" data-scroll-target="#definition-categorical-factor-variable">Definition : Categorical Factor Variable</a></li>
  <li><a href="#graphing-the-categorical-plot" id="toc-graphing-the-categorical-plot" class="nav-link" data-scroll-target="#graphing-the-categorical-plot">Graphing : The Categorical Plot</a></li>
  </ul></li>
  <li><a href="#defining-variables-in-r" id="toc-defining-variables-in-r" class="nav-link" data-scroll-target="#defining-variables-in-r">Defining Variables in R</a>
  <ul class="collapse">
  <li><a href="#video-defining-numeric-variables-in-r" id="toc-video-defining-numeric-variables-in-r" class="nav-link" data-scroll-target="#video-defining-numeric-variables-in-r">Video : Defining Numeric Variables in R</a></li>
  <li><a href="#video-graphing-numeric-variables-in-r" id="toc-video-graphing-numeric-variables-in-r" class="nav-link" data-scroll-target="#video-graphing-numeric-variables-in-r">Video : Graphing Numeric Variables in R</a></li>
  <li><a href="#video-defining-categorical-variables-in-r" id="toc-video-defining-categorical-variables-in-r" class="nav-link" data-scroll-target="#video-defining-categorical-variables-in-r">Video : Defining Categorical Variables in R</a></li>
  <li><a href="#video-graphing-categorical-variables-in-r" id="toc-video-graphing-categorical-variables-in-r" class="nav-link" data-scroll-target="#video-graphing-categorical-variables-in-r">Video : Graphing categorical variables in R</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#part-2-working-with-datasets" id="toc-part-2-working-with-datasets" class="nav-link" data-scroll-target="#part-2-working-with-datasets">Part 2 : Working with Datasets</a>
  <ul class="collapse">
  <li><a href="#the-dataframe" id="toc-the-dataframe" class="nav-link" data-scroll-target="#the-dataframe">The Dataframe</a>
  <ul class="collapse">
  <li><a href="#definition-rows-and-columns" id="toc-definition-rows-and-columns" class="nav-link" data-scroll-target="#definition-rows-and-columns">Definition : Rows and Columns</a></li>
  <li><a href="#definition-indexing" id="toc-definition-indexing" class="nav-link" data-scroll-target="#definition-indexing">Definition : Indexing</a></li>
  </ul></li>
  <li><a href="#test-yourself" id="toc-test-yourself" class="nav-link" data-scroll-target="#test-yourself">Test Yourself!</a>
  <ul class="collapse">
  <li><a href="#videos-how-to-navigate-datasets-in-r" id="toc-videos-how-to-navigate-datasets-in-r" class="nav-link" data-scroll-target="#videos-how-to-navigate-datasets-in-r">Videos : How to Navigate Datasets in R</a></li>
  <li><a href="#check-in-navigating-variables-and-datasets-with-indexing" id="toc-check-in-navigating-variables-and-datasets-with-indexing" class="nav-link" data-scroll-target="#check-in-navigating-variables-and-datasets-with-indexing">Check-In : Navigating Variables and Datasets with Indexing</a></li>
  </ul></li>
  <li><a href="#the-.csv-file" id="toc-the-.csv-file" class="nav-link" data-scroll-target="#the-.csv-file">The .csv File</a>
  <ul class="collapse">
  <li><a href="#definition-the-.csv-file" id="toc-definition-the-.csv-file" class="nav-link" data-scroll-target="#definition-the-.csv-file">Definition : The .csv File</a></li>
  <li><a href="#videos-how-to-load-datasets-in-r" id="toc-videos-how-to-load-datasets-in-r" class="nav-link" data-scroll-target="#videos-how-to-load-datasets-in-r">Videos : How to Load Datasets in R</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#practice-quiz-2" id="toc-practice-quiz-2" class="nav-link" data-scroll-target="#practice-quiz-2">Practice Quiz 2</a></li>
  <li><a href="#tldr" id="toc-tldr" class="nav-link" data-scroll-target="#tldr">TLDR</a></li>
  <li><a href="#chapter-appendix-r-commands" id="toc-chapter-appendix-r-commands" class="nav-link" data-scroll-target="#chapter-appendix-r-commands">Chapter Appendix : R Commands</a>
  <ul class="collapse">
  <li><a href="#r-code-creating-variables-in-r" id="toc-r-code-creating-variables-in-r" class="nav-link" data-scroll-target="#r-code-creating-variables-in-r">R Code : Creating Variables in R</a></li>
  <li><a href="#numeric-variables-in-r" id="toc-numeric-variables-in-r" class="nav-link" data-scroll-target="#numeric-variables-in-r">Numeric Variables in R</a></li>
  <li><a href="#string-variables" id="toc-string-variables" class="nav-link" data-scroll-target="#string-variables">String Variables</a></li>
  <li><a href="#r-commands-for-importing-and-navigating-data" id="toc-r-commands-for-importing-and-navigating-data" class="nav-link" data-scroll-target="#r-commands-for-importing-and-navigating-data">R Commands for Importing and Navigating Data</a></li>
  <li><a href="#r-commands-for-visualizing-data" id="toc-r-commands-for-visualizing-data" class="nav-link" data-scroll-target="#r-commands-for-visualizing-data">R Commands for Visualizing Data</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/1R_WhyStats.html">Describing People</a></li><li class="breadcrumb-item"><a href="../chapters/2R_Data.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Data</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Hello! In this week’s reading, you’ll learn how to work with data in R - first how to navigate datasets, and then how to graph (and think critically about) both categorical and continuous variables.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/2_medicalposter.jpg" class="img-fluid figure-img" alt="a chinese medical poster, depicting a human on the left and a mechanical version of the human on the right. for example, the human is holding up a weight with their arm, whereas the mechanical human has a crane for an arm."></p>
<figcaption>Chinese medical poster, 1933 (ref <a href="https://www.nlm.nih.gov/hmd/chineseposters/understanding.html">US NLM</a>; image source <a href="http://www.notechmagazine.com/2009/06/the-body-is-a-machine.html">here</a>)</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
To-Do List:
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Read this document and watch the videos.
<ul>
<li>Part 1 : On creating variables in R</li>
<li>Part 2 : In navigating and installing datasets in R.</li>
</ul></li>
<li>Complete the check-in and practice quiz.</li>
<li>Take Quiz 2.</li>
</ul>
</div>
</div>
<section id="part-1-defining-data" class="level1">
<h1>Part 1 : Defining Data</h1>
<p>Researchers seeking to bring a scientific approach to psychology love data, and aim to convert complex human thoughts, feelings, and behaviors into numbers. This is called <strong>quantitative data,</strong> and is the default approach almost all modern research psychologists take. For example:&nbsp;</p>
<ul>
<li><p>Psychologists will quantify <strong>affect</strong> using heart rate monitors, finger temperature gauges, or even simple rating scales of how people are feeling (quick, how bored are you right now on a scale from 0 (not bored; super engaged professor!) to 10 (….most bored ever; surprised I’m even reading this right now)….see, you are just a number!)</p></li>
<li><p>Psychologists often quantify <strong>behavior</strong> by measuring reaction time, the number of times a person fidgets in a chair, how far a person will sit from another person in a study, the speed of a group. And even qualitative data - like a person’s journal entry - would be turned into hard numbers by a researcher (who would ask a team of research assistants to read the journal and then count or provide a subjective rating to what they observe. this is called <strong>behavioral coding</strong>; we’ll learn about it later. remind me if I forget.)</p></li>
<li><p>Neuroscientists quantify&nbsp; <strong>cognition</strong> in terms of voxel activation in the brain, or a sleep researcher might ask participants to write down their dreams in a journal, which then a team of research assistants would read and convert into….you guessed it…numbers (e.g., number of times person dreamt about water or their parents; how stressful the dream seemed to the reader; etc.)</p></li>
</ul>
<p>While we will learn more about the various ways psychologists collect data later this semester, for now it’s important to acknowledge that these numbers have error (called <strong>measurement error</strong>), a fair amount of work in psychology goes into learning how to reduce measurement error as much as possible, and the existence of measurement error is one form of error that will contributes to the ERROR term in our linear models.</p>
<p>Quantitative data takes two forms that we will see in this class - <strong>numeric</strong> (sometimes called <strong>continuous data</strong>)&nbsp; and <strong>categorical data (</strong>sometimes called “string” data).&nbsp;</p>
<section id="numeric-variables" class="level2">
<h2 class="anchored" data-anchor-id="numeric-variables">Numeric variables</h2>
<section id="definition-numeric-variable" class="level3">
<h3 class="anchored" data-anchor-id="definition-numeric-variable">Definition : Numeric Variable</h3>
<p>Numeric variables are when the value of the variable is a number (e.g., your Extraversion score is 62 on a scale from 0 to 100; or you said “um” fifty times yesterday, or scrolled your phone five times since starting this reading.&nbsp;</p>
<p><strong>Continuous variables</strong> are a special type of numeric variable, with the idea that values of the variable represent an “infinite” range of possibilities.</p>
<p>We often simplify complexity into discrete groups, but for most complex phenomena, I believe that it’s best to think of life as a spectrum. For example, while I look at my walls and say “they are blue”, a physicist who really understands color theory would be able to interpret the wavelength of light that is being reflected off these walls, and understands that that wavelength really just a point on an infinite spectrum (bound by a certain range).</p>
<p><img src="images/2_lightspectrum.png" class="img-fluid"></p>
<p>Psychologists working in R often use numeric data, and see this as a list (or vector) of numbers. For example, below is data on the narcissism (variable = NPI; a measure of how self-absorbed; self-interested) of a group of Berkeley Haas MBA students were<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>haas <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"./chapter_data/hormone_data.csv"</span>, <span class="at">stringsAsFactors =</span> T) </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>haas<span class="sc">$</span>NPI</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] 3.43 4.40 3.13   NA 3.00   NA 3.05   NA   NA 3.63 3.95 3.08 3.83 3.23 3.80
 [16] 1.80 3.68 3.48 2.73 3.40 2.95 3.65 2.88 2.50 3.13 2.75 3.00 3.15 3.30 3.20
 [31] 2.43 3.13   NA 3.33 2.88 2.55 3.35 3.30 3.28 3.08 2.48 2.78 4.58 2.53 2.78
 [46] 2.88   NA 3.43 2.48 3.50 2.40 3.28 3.63 3.13 2.05 2.98 2.53 3.45 2.80 2.60
 [61] 2.05 2.60 2.73 3.25 2.78 2.93 3.08 3.33 4.05 3.65 3.15 3.33 3.98 4.48 3.00
 [76] 3.00 3.25 4.28 3.13 3.83 3.98 4.13 3.73 3.28 2.85 3.28 3.70 3.03 3.38 2.88
 [91] 3.20 3.40 3.70 3.50 2.58 2.90 3.00 3.35 2.63   NA   NA 4.05 3.43 4.28 3.00
[106] 3.10 3.13 2.83 2.78 2.33 2.68 2.88 2.53 3.80 3.48 3.15 4.38 3.73 3.80 2.60
[121] 3.38 3.13</code></pre>
</div>
</div>
<p><strong>Professor Interpretation</strong> I learn a lot just from this simple output!</p>
<ul>
<li><strong>haas &lt;- read.csv(“./chapter_data/hormone_data.csv”, stringsAsFactors = T”)</strong> is the R command that loads the dataset. Note that the path to the datafile - hormone_data.csv - is specific to the way I’ve stored these data in my file system. You’ll learn below how to change this to access your own dataset :)</li>
<li><strong>haas$NPI</strong> is the R command that was used to generate the output below; a list of 122 individual Narcissism scores.
<ul>
<li>I know there’s 122 individual scores because R is keeping count for me using indexing; the numbers in brackets. [1] shows that the first person in the dataset has a narcissism (NPI) score of 3.43; [118] 3.73 shows that this is the score for the 118th person in the dataset, and then I can count up to 122. There are much faster ways to do this, but I can do it this way too :)</li>
<li>I also see there are a few missing data points in the responses - these are marked as NA. This could be people who didn’t complete the survey or were excluded for other reasons (e.g.&nbsp;missing data).</li>
</ul></li>
</ul>
</section>
<section id="graphing-the-histogram" class="level3">
<h3 class="anchored" data-anchor-id="graphing-the-histogram">Graphing : The Histogram</h3>
<p><strong>The Histogram</strong> is a commonway researchers illustrate numeric variables. We will learn more about principles of good graphing this semester, but the KEY IDEA is to always always always graph your data because A PICTURE IS WORTH 1000 WORDS.&nbsp;</p>
<p>The histogram organizes data - you lose the individual values, but gain understanding in seeing how data are grouped together, which helps you observe patterns and get a quick summary of the variable.&nbsp;</p>
<p>There are two dimensions of a histogram :&nbsp;</p>
<ul>
<li><p><strong>the x-axis</strong> (the horizontal axis; what goes across) : displays the values of the variable as organized into groups (or “breaks”, in R).&nbsp;</p></li>
<li><p><strong>the y-axis</strong> (the vertical axis; what goes up and down) : displays the frequency (or count) of the individuals in the data who “belong” to that group.</p></li>
</ul>
<p>Let’s look at our MBA friends again, through the power of a histogram. As you look at a graph, it’s important to practice thinking about what you learn from the data. Let’s avoid fancy stats terminology for now; it’s not necessary for our purposes!!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(haas<span class="sc">$</span>NPI, <span class="at">xlab =</span> <span class="st">"Narcissism Score"</span>, <span class="at">col =</span> <span class="st">'black'</span>, <span class="at">bor =</span> <span class="st">'white'</span>, <span class="at">main =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2R_Data_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p><strong>the code :</strong> this code draws a histogram using the <code>hist()</code> function. I’ve also added several <code>arguments</code> that change some of the default settings to give the graph some <em>digital style.</em></p>
<ul>
<li><p><code>xlab</code> gives the x-axis of the graph a nice label.</p></li>
<li><p><code>col</code>changes the color of the bars to black.</p></li>
<li><p><code>bor</code> changes the color of the lines surrounding the bars to white.</p></li>
<li><p><code>main</code> changes the title. In this case, <code>""</code> sets the title to be nothing, so there’s no title.</p></li>
</ul></li>
<li><p><strong>the graph :</strong> okay, what did R do!</p>
<ul>
<li><p><strong>x-axis :</strong> this reports the grouped values of the individual narcissism scores.&nbsp;</p></li>
<li><p><strong>y-axis :</strong> this reports how many people were in each group.</p></li>
</ul></li>
<li><p><strong>professor interpretation with no fancy stats language needed.</strong></p>
<ul>
<li><p>most people (around 42?) had a narcissism score between 3 and 3.5</p></li>
<li><p>a few people were really high in narcissism…above a 4.5. I’m not sure from the graph exactly how many people were in this group, or what their score was.</p></li>
<li><p>a few people were really low in narcissism…below a 2. Again, I’m not sure from the graph exactly how many people were in this group, or what their score was, but I see their humble selves!</p></li>
<li><p>I also notice that this is not a super large study - the frequencies on the y-axis are relatively low numbers.</p></li>
</ul></li>
</ul>
</section>
<section id="activity-think-about-data" class="level3">
<h3 class="anchored" data-anchor-id="activity-think-about-data">Activity : Think about Data!</h3>
<p>Okay, your turn. Below is a graph from the same MBA students, but this time measuring their testosterone levels. Look over the graph, THINK about what you see, and then expand the textbox below (click on the arrow on the right side of the green box) to see what I wrote.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(haas<span class="sc">$</span>test, </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Testosterone Level"</span>, <span class="at">main =</span> <span class="st">""</span>, </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">'black'</span>, <span class="at">bor =</span> <span class="st">'white'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2R_Data_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
PROFESSOR SPOILERS : Expand this textbox when you are ready by clicking on the arrow —&gt;
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li><strong>the graph</strong>
<ul>
<li><strong>x-axis</strong> : this reports the grouped values of the individual testosterone scores, measured in some kind of density (pg/ML)</li>
<li><strong>y-axis</strong> : this reports how many people were in each group.</li>
</ul></li>
<li><strong>what I see and observe with no stats language :</strong>
<ul>
<li>most people (around 25+12+20 = 77) had a testosterone level between 50 and 100.</li>
<li>there were no scores below zero (which makes sense) and one person who had a very high level of testosterone. I’m not a hormone researcher, but the non-negative values seems good, and I might want to make sure that there wasn’t some data entry error for the extreme score.</li>
<li>Again, I notice that this is not a super large study….and these relatively low numbers seem similar to the narcissism data, which makes sense since they came from the same study.</li>
</ul></li>
</ul>
</div>
</div>
</div>
</section>
</section>
<section id="categorical-factor-variable" class="level2">
<h2 class="anchored" data-anchor-id="categorical-factor-variable">Categorical Factor Variable</h2>
<section id="definition-categorical-factor-variable" class="level3">
<h3 class="anchored" data-anchor-id="definition-categorical-factor-variable">Definition : Categorical Factor Variable</h3>
<p>A categorical factor variable is when the values of the variable represent different groups, usually labeled with some kind of word. Categories are often useful and simple ways to group individuals together. For example, when I see a color, I don’t ever describe it in terms of its color hex code or specific wavelength - I just call it by the simple primary color that I got from the crayola box; maybe the 24 color version if I’m feeling fancy.</p>
<p>Which of the shades below would you call blue?<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/2_shadesofcyan.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="a 3x3 grid of different squares that are shades of blue and green" width="388"></p>
</figure>
</div>
<p>The broad label for the variable is called <strong>the factor</strong>, and the specific groups of data are called <strong>levels</strong>. So in the color example, the category of color would be the factor, and the different groups of color would be the levels.</p>
<p>As another example, researchers can measure gender with categories such as female, male, transgender, and other. Identify the factor and levels in this example.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What are the factors and levels in the example above?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Factor : would be the variable of gender. Generally there’s one factor label for each variable.</li>
<li>Level : would be the categories female, male, transgender, and other.</li>
</ul>
</div>
</div>
</div>
<section id="culture-in-statistics-gender-identity" class="level4">
<h4 class="anchored" data-anchor-id="culture-in-statistics-gender-identity">Culture in Statistics : Gender Identity</h4>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td><img src="../images/doff_intro_mickey.png" class="img-fluid"></td>
<td><p>Hi folks! It’s me again, Open-Source Mickey Mouse to talk with you about the idea that statistics has a culture that is socially constructed by people like you! We live in a society where people in positions of power often have very narrow definitions of what it means to be a person! This manifests in all sorts of ways - you probably feel this pressure when you think about what it means to be a “successful student”.</p>
<p>One domain where this is particularly relevant is in the area of gender identity. While many people identify as “male” or “female”, some people don’t fit into these categories. (Seems pretty simple to me to let folks exist as they want! But I’m just a poor public servant.) Yet as folks in power have recently <a href="https://www.motherjones.com/politics/2025/01/trumps-definitions-of-male-and-female-are-nonsense-science-with-staggering-ramifications/">forced this narrow binary view of gender identity onto everyone</a>, it becomes even more critical to engage with these ideas and try to define a science that can capture the complexity of human life in ways that let people be their full selves.</p></td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td><p>Unfortunately, most psychological researchers still hold on to Male / Female binaries in the way they measure gender or sex, yet there are many reasons - both scientific and humanistic - to give people more range to express important aspects of their identity<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>.</p>
<p>Indeed, categories almost always oversimplify the complexity of life, yet are often used by people (and researchers) because they can sometimes be useful and simple shortcuts for us to understand the world.</p>
<p>If you are simply interested in doing a superficial survey of a variable like race, ethnicity, or gender, then I think categorical data can be a fine -if often unscientific - approach, and would recommend giving all people the chance to express their identity in some way.</p>
<p>However, if you are interested in really digging into a variable, then a continuous approach is almost always best. We’ll discuss more on how to do this in a few weeks when we learn about continuous variables and likert scales.</p></td>
<td><p><strong><img src="images/2_fb_gender.png" class="img-fluid" alt="facebook’s attempt at measuring more complex categories."></strong></p>
<p><a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
<p><strong><img src="images/2_genderspectrum.png" class="img-fluid" alt="a continuous approach to measuring gender."></strong><a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p></td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="graphing-the-categorical-plot" class="level3">
<h3 class="anchored" data-anchor-id="graphing-the-categorical-plot">Graphing : The Categorical Plot</h3>
<p>The histogram only describes a graph for numeric data, since it organizes numbers into groups (it kind of turns complex variation into more simple categories). When the variable is categorical, people call it a plot 🤷.</p>
<p>This graph looks very similar to our histogram :&nbsp;</p>
<ul>
<li><p><strong>the x-axis</strong> (the horizontal axis; what goes across) : displays the levels of the factor variable.</p></li>
<li><p><strong>the y-axis</strong> (the vertical axis; what goes up and down) : displays the frequency (or count) of the individuals in the data who “belong” to each group.</p></li>
</ul>
<p>Alright, back to our good MBA friends. This is a graph of the categorical variable “sex”. Again, look over the graph, THINK about what you see (no stats terminology; what do you learn!), and then highlight my text to see what I wrote about.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(haas<span class="sc">$</span>sex, <span class="at">col =</span> <span class="st">'black'</span>, <span class="at">bor =</span> <span class="st">'white'</span>, <span class="at">xlab =</span> <span class="st">"Sex"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2R_Data_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p><strong>The Code :</strong> this code draws a histogram using the <code>plot()</code> function. Note that I’ve asked R to <code>plot</code> the variable <code>haas$sex</code>. I’ve also added several <code>arguments</code> that change some of the default settings to give the graph some <em>digital style.</em></p>
<ul>
<li><p><code>xlab</code> gives the x-axis of the graph a nice label.</p></li>
<li><p><code>col</code>changes the color of the bars to black.</p></li>
<li><p><code>bor</code> changes the color of the lines surrounding the bars to white.</p></li>
</ul></li>
<li><p><strong>The Graph :</strong></p>
<ul>
<li><p><strong>x-axis :</strong> this reports levels (female; male) of the categorical factor variable Sex.&nbsp;</p></li>
<li><p><strong>y-axis :</strong> this reports how many people were in each group.</p></li>
</ul></li>
<li><p><strong>What I see and observe with no stats language :</strong></p>
<ul>
<li><p>It appears that the researchers only measured sex as a f/m binary (or that no participants reported a category other than female or male).</p></li>
<li><p>there were more males than females in this dataset. This matches my perception / stereotype of what a typical MBA program might look like; however I looked into it and Haas reports a larger percentage of female enrollments in the MBA program; so our data may not serve as a representative sample of the true population.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a><br>
</p></li>
</ul></li>
</ul>
</section>
</section>
<section id="defining-variables-in-r" class="level2">
<h2 class="anchored" data-anchor-id="defining-variables-in-r">Defining Variables in R</h2>
<p>Below are some videos, and R code, that review how to define a variable in R. Yeah!</p>
<p>We practiced this in lecture, but below are some videos that go over how to define variables in R. Yeah!!!! I’m not going to share the Rscripts I’m using for these videos, since I think there’s value in typing this out yourself to get that muscle memory in 💪🤘 but let me know if you disagree / there’s a reason to provide them to y’all!</p>
<section id="video-defining-numeric-variables-in-r" class="level3">
<h3 class="anchored" data-anchor-id="video-defining-numeric-variables-in-r">Video : Defining Numeric Variables in R</h3>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/0pXGqGDSySM" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<ul>
<li><p>objects - assign function for numerical data</p></li>
<li><p>c() : combining data together.</p></li>
<li><p>length() : the number of objects</p></li>
</ul>
</section>
<section id="video-graphing-numeric-variables-in-r" class="level3">
<h3 class="anchored" data-anchor-id="video-graphing-numeric-variables-in-r">Video : Graphing Numeric Variables in R</h3>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/lmXQ2BhQNuo" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<ul>
<li><p>hist() : a graph</p></li>
<li><p>changing arguments : xlab, ylab, main</p></li>
</ul>
</section>
<section id="video-defining-categorical-variables-in-r" class="level3">
<h3 class="anchored" data-anchor-id="video-defining-categorical-variables-in-r">Video : Defining Categorical Variables in R</h3>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/CFXRxfaadIw" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<ul>
<li>categorical data (“string”)</li>
<li>as.factor() : to convert a string to a categorical variable</li>
<li>levels() : to see the levels of your categorical variable.</li>
</ul>
</section>
<section id="video-graphing-categorical-variables-in-r" class="level3">
<h3 class="anchored" data-anchor-id="video-graphing-categorical-variables-in-r">Video : Graphing categorical variables in R</h3>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/Fmai9Ltpa5I" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<ul>
<li>plot()</li>
<li>changing arguments : col, bor, main; xlab; ylab</li>
</ul>
</section>
</section>
</section>
<section id="part-2-working-with-datasets" class="level1">
<h1>Part 2 : Working with Datasets</h1>
<section id="the-dataframe" class="level2">
<h2 class="anchored" data-anchor-id="the-dataframe">The Dataframe</h2>
<section id="definition-rows-and-columns" class="level3">
<h3 class="anchored" data-anchor-id="definition-rows-and-columns">Definition : Rows and Columns</h3>
<p>As a researcher, you’ll be interested in understanding not only one variable at a time, but will be interested in a dataset - multiple variables about an individual that are organized - in order to see how variables are related to each other (remember : this is a function of the linear model).</p>
<p>The datasets in our class will be stored on Dropbox; you can find a link to this on bCourses (see below).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/2_dropboxOnBcourses.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
<p>You’ll learn how to load these datasets later in this lecture. For now, what is a dataset?</p>
<p>A dataset is really a <strong>dataframe</strong> - a two-dimensional way to organize data - and takes the following structure in this class.</p>
<ul>
<li><p><strong>the rows</strong> define the individual in the dataset.&nbsp;rows go across horizontally, like a rowboat going across a lake.</p></li>
<li><p>the columns define the variables in the dataset. &nbsp;go up and down vertically; like what might support a bridge.</p></li>
</ul>
<p>Look at the example below - again from our budding MBAs in the Haas program. What do you observe about the rows and columns? What does this tell you about the dataset?</p>
<p><strong><img src="images/2_haas_dataframe.png" class="img-fluid"></strong><br>
<br>
In the example dataframe above - I see 5 rows (representing 5 individuals) and five columns (representing five variables like the person’s <strong>age</strong>, their <strong>sex,</strong> their <strong>test</strong>osterone levels, political <strong>ideo</strong>logy, and their <strong>NPI</strong> (Narcissism) score.&nbsp; or their Race, etc.) Note that the names of the variables do not count as a row, since these are not individuals in the dataset, and you would need to know more about the dataset to know that ideo = political ideology, or test = testosterone. I also see that R is helpfully telling me that this is only a snapshot of the entire dataset - the whole dataframe has 122 entries (rows), meaning that there’s 122 MBA students in this dataset, and 5 total columns (which we can all see here.)</p>
<p>As a researcher, you have access to an entire dataset (either collected by you or another researcher) that organizes multiple variables for each individual. This semester, we’ll work with a variety of datasets on different psychological topics - not just haas students.</p>
</section>
<section id="definition-indexing" class="level3">
<h3 class="anchored" data-anchor-id="definition-indexing">Definition : Indexing</h3>
<p>The dataset gives us access to all the individual rows and columns at once, we will often want to focus on one specific variable (or individual) at a time. <strong>Indexing</strong> refers to a flexible method of selecting a specific set of data from a larger collection. Previously’ we’ve seen indexing when asking R to produce a large set of numbers; for example asking it to count from 1 to 100.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">:</span><span class="dv">100</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1]   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
 [19]  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
 [37]  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
 [55]  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
 [73]  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
 [91]  91  92  93  94  95  96  97  98  99 100</code></pre>
</div>
</div>
<p>The indexing shows up as brackets next to the actual data, and is way for R to index that the [1]st data entry is the number 1, the [24]th entry is the number 24, and so on.</p>
<p>When I ask R to show me the dataset haas, the output can be overwhelming. Below is what R shows you when you ask to see the haas dataset. And this is a relatively small dataset with just 122 individuals (rows) and five variables (columns).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>haas</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    age    sex   test ideo  NPI
1    NA   male     NA   NA 3.43
2    NA   male 143.89   NA 4.40
3    NA   male     NA   NA 3.13
4    30   male     NA    4   NA
5    28   male     NA    4 3.00
6    33 female     NA    5   NA
7    NA   male     NA   NA 3.05
8    NA   male     NA   NA   NA
9    NA   male  77.95   NA   NA
10   NA   male     NA   NA 3.63
11   26   male 126.29    3 3.95
12   31   male  59.48    5 3.08
13   27   male  89.45    4 3.83
14   27   male  82.80    3 3.23
15   28   male  97.39    4 3.80
16   30   male  54.80    4 1.80
17   28   male  46.07    4 3.68
18   24   male     NA    4 3.48
19   32   male  87.40    3 2.73
20   25   male  85.01    4 3.40
21   27   male     NA    3 2.95
22   25   male     NA    4 3.65
23   24   male 102.86    3 2.88
24   28   male  73.60    3 2.50
25   27   male     NA    2 3.13
26   29   male  90.68    4 2.75
27   28   male  44.70    3 3.00
28   29   male     NA    4 3.15
29   30   male  77.61    4 3.30
30   26   male  57.20    5 3.20
31   31   male  49.92    4 2.43
32   28   male     NA    3 3.13
33   32   male     NA    5   NA
34   27   male  85.01    2 3.33
35   32   male  74.86    2 2.88
36   27   male 125.89    3 2.55
37   29   male  77.07    4 3.35
38   30   male     NA    4 3.30
39   26   male  30.54    4 3.28
40   27   male  73.76    3 3.08
41   32   male  65.61    3 2.48
42   29   male  51.23    4 2.78
43   28   male  85.17    3 4.58
44   28   male     NA    3 2.53
45   29   male  57.14    2 2.78
46   30   male  65.31    4 2.88
47   28   male  53.07    4   NA
48   28   male 104.65    3 3.43
49   31   male  90.32    3 2.48
50   NA female  24.71   NA 3.50
51   26 female  20.99    3 2.40
52   27 female     NA    4 3.28
53   28 female     NA    3 3.63
54   28 female   5.51    5 3.13
55   27 female  40.49    4 2.05
56   25 female  35.05    2 2.98
57   26 female  57.71    4 2.53
58   26 female  27.36    4 3.45
59   27 female  59.37    3 2.80
60   26 female  21.63    3 2.60
61   29 female     NA    3 2.05
62   25 female     NA    7 2.60
63   37 female  39.50    4 2.73
64   28 female  42.35    4 3.25
65   24 female  32.42    3 2.78
66   29   male  97.63    4 2.93
67   28   male 131.51    3 3.08
68   26   male     NA    4 3.33
69   27   male     NA    5 4.05
70   29   male     NA    2 3.65
71   27   male 140.53    2 3.15
72   26   male     NA    3 3.33
73   28   male     NA    3 3.98
74   22   male  90.88    5 4.48
75   29   male 148.24    5 3.00
76   29   male 132.24    4 3.00
77   27   male  82.43    4 3.25
78   26   male  73.43    4 4.28
79   35   male     NA    2 3.13
80   27   male 100.49    4 3.83
81   25   male  94.31    4 3.98
82   27   male  72.53    2 4.13
83   30   male 133.35    4 3.73
84   27   male  59.77    4 3.28
85   30   male  91.83    4 2.85
86   29   male  82.13    3 3.28
87   30   male 172.15    3 3.70
88   29   male 228.17    2 3.03
89   27   male 133.70    3 3.38
90   27   male  89.24    4 2.88
91   28   male  88.62    3 3.20
92   28   male  86.83    4 3.40
93   25   male 138.65    4 3.70
94   33   male  59.75    4 3.50
95   28   male  46.30    3 2.58
96   31   male 107.02    3 2.90
97   24   male  60.16    2 3.00
98   26   male     NA    4 3.35
99   27   male 107.71    3 2.63
100  23   male  99.64    2   NA
101  32   male 131.51    3   NA
102  29   male  91.94    4 4.05
103  25   male  53.67    3 3.43
104  25   male     NA    4 4.28
105  27 female     NA    4 3.00
106  27 female  59.24    2 3.10
107  30 female  28.03    5 3.13
108  28 female  33.38    5 2.83
109  26 female  53.31    4 2.78
110  28 female  27.53    4 2.33
111  29 female  16.89    4 2.68
112  25 female  51.53    4 2.88
113  26 female  37.15    4 2.53
114  27 female  50.55    2 3.80
115  28 female     NA    4 3.48
116  28 female  41.35    5 3.15
117  29 female  64.66    5 4.38
118  24 female  37.95    2 3.73
119  27 female  54.26    4 3.80
120  27 female     NA    4 2.60
121  27 female 113.41    4 3.38
122  29 female  41.35    3 3.13</code></pre>
</div>
</div>
<p>I am overwhelmed with data. So it will be important to find ways to target the data that we want. There are several ways we can do this!</p>
<p>Because a dataset has two different dimensions, we have to use two coordinates to index the dataset - one coordinate for the row(s) that we want to focus on, and one coordinate for the column(s) that we want to focus on.<br>
</p>
<section id="indexing-an-entire-dataset" class="level4">
<h4 class="anchored" data-anchor-id="indexing-an-entire-dataset">Indexing an Entire Dataset</h4>
<p>Because a dataset has two different dimensions, we have to use two coordinates to index the dataset - one coordinate for the row(s) that we want to focus on, and one coordinate for the column(s) that we want to focus on.</p>
<ul>
<li><p><code>data</code> # this reports the entire dataset. In the example to the right, I’ve typed in haas (since this is the name of the dataset in this example) and see the dataset reported.</p></li>
<li><p><code>data[i, j]</code> # this code returns a specific row (i), and a specific column (j). The convention is to use the letter i for a row first, then j for a column <strong>[you can remember this order as RC Car, or R is Cool].</strong> For example</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>haas[<span class="dv">2</span>,<span class="dv">3</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 143.89</code></pre>
</div>
</div>
<p>Shows me that R has highlighted the second row and third column of the dataset - the second person’s testosterone level is 143.89 units.</p></li>
</ul>
<p><code>data[ , j]</code> # if you leave a blank for the rows, then R will return all of the rows, and whatever column you specify. This can be good for looking at a specific variable for all individuals. For example, the following code returns all of the testosterone data (the third column).</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="in">haas[,3]</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><p><code>data[i, ]</code> # &nbsp;if you leave a blank for the column, then you would see all of the columns for a specific row. This can be good for looking at a specific individual’s entire dataset; such as all of participant 2’s data below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>haas[<span class="dv">2</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  age  sex   test ideo NPI
2  NA male 143.89   NA 4.4</code></pre>
</div>
</div></li>
<li><p><code>haas[i:i, c(j, j)]</code> # you can adapt this code to give a range of values too. for example, if I want to see rows 4-10 and columns 1 and 3, I would run the following code.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>haas[<span class="dv">4</span><span class="sc">:</span><span class="dv">10</span>, <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   age  test
4   30    NA
5   28    NA
6   33    NA
7   NA    NA
8   NA    NA
9   NA 77.95
10  NA    NA</code></pre>
</div>
</div></li>
</ul>
</section>
<section id="indexing-a-single-variable" class="level4">
<h4 class="anchored" data-anchor-id="indexing-a-single-variable">Indexing a Single Variable</h4>
<ul>
<li><p><code>data$variable</code> # You can also use the $ (dollar sign) in R to reference a single variable from a dataset. This is very useful, because you can use the name of the variable instead of the numerical index. So, for example, if I want to highlight the testosterone levels of the haas dataset, I would run the following :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>haas<span class="sc">$</span>test</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1]     NA 143.89     NA     NA     NA     NA     NA     NA  77.95     NA
 [11] 126.29  59.48  89.45  82.80  97.39  54.80  46.07     NA  87.40  85.01
 [21]     NA     NA 102.86  73.60     NA  90.68  44.70     NA  77.61  57.20
 [31]  49.92     NA     NA  85.01  74.86 125.89  77.07     NA  30.54  73.76
 [41]  65.61  51.23  85.17     NA  57.14  65.31  53.07 104.65  90.32  24.71
 [51]  20.99     NA     NA   5.51  40.49  35.05  57.71  27.36  59.37  21.63
 [61]     NA     NA  39.50  42.35  32.42  97.63 131.51     NA     NA     NA
 [71] 140.53     NA     NA  90.88 148.24 132.24  82.43  73.43     NA 100.49
 [81]  94.31  72.53 133.35  59.77  91.83  82.13 172.15 228.17 133.70  89.24
 [91]  88.62  86.83 138.65  59.75  46.30 107.02  60.16     NA 107.71  99.64
[101] 131.51  91.94  53.67     NA     NA  59.24  28.03  33.38  53.31  27.53
[111]  16.89  51.53  37.15  50.55     NA  41.35  64.66  37.95  54.26     NA
[121] 113.41  41.35</code></pre>
</div>
</div></li>
<li><p><code>data$variable[i]</code> # We can then use indexing to narrow this down. Because a variable only has one dimension (it’s just a collection of individuals; not rows and individuals) I only need to use one coordinate to index the specific individual(s) I want to find.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>haas<span class="sc">$</span>test[<span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 143.89</code></pre>
</div>
</div>
<ul>
<li><p><code>data$variable[i:i]</code> # Can be used to find a range of individuals. These numbers need to be sequential for this code to work.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>haas<span class="sc">$</span>test[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]     NA 143.89     NA</code></pre>
</div>
</div></li>
<li><p><code>data$variable[c(i,i,i)]</code> # If you want to find individuals who are not next to each other, you need to use the <strong>c (combine) function</strong> to combine multiple coordinates together. You can have as many coordinates here as you want. For example :&nbsp;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>haas<span class="sc">$</span>test[<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">14</span><span class="sc">:</span><span class="dv">18</span>, <span class="dv">116</span><span class="sc">:</span><span class="dv">118</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 143.89     NA  82.80  97.39  54.80  46.07     NA  41.35  64.66  37.95</code></pre>
</div>
</div></li>
</ul>
</section>
</section>
</section>
<section id="test-yourself" class="level2">
<h2 class="anchored" data-anchor-id="test-yourself">Test Yourself!</h2>
<p>Okay, practice time. Use the haas dataset and your knowledge of indexing to identify what R would show if you typed in the following commands (no R required)</p>
<ul>
<li>haas$age[47]</li>
<li>haas$NPI[1:3]</li>
<li>haas[51,2]</li>
<li>haas[60, ]</li>
<li>haas[ , 6]</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answer Key
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>28</li>
<li>3.43 4.40 3.13</li>
<li>female</li>
<li>26 female 21.63 3 2.6</li>
<li>you would get an error; there is no 6th column.</li>
</ul>
</div>
</div>
</div>
<section id="videos-how-to-navigate-datasets-in-r" class="level3">
<h3 class="anchored" data-anchor-id="videos-how-to-navigate-datasets-in-r">Videos : How to Navigate Datasets in R</h3>
<p>Let’s get some more practice with some actual data. Before we learn how to import data in R, we can work with a super exciting dataset that is already part of the R program - a dataset on the weights of chickens (chkwt).</p>
<p>Watch the two videos below to see how I navigate this dataset; here’s a <a href="https://www.dropbox.com/scl/fi/e9l24v1vshdjih7rctxcn/navigating_data.R?rlkey=st0f3hzkrkmha4u4224f6n43i&amp;dl=0">link to the RScript</a> that I use in the videos.&nbsp;</p>
<section id="video-checking-datasets-in-r" class="level4">
<h4 class="anchored" data-anchor-id="video-checking-datasets-in-r">Video : Checking Datasets in R</h4>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/TaonMS3b0pU" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<ul>
<li><p><strong>length() :</strong> counts the number of objects (variables) in a dataset (or any object)</p></li>
<li><p><strong>nrow() :</strong> counts the number of rows (participants) in a dataset</p></li>
</ul>
<p><strong>head() :</strong> looks at the first six rows of a dataset</p>
</section>
<section id="video-navigating-datasets-with-indexing" class="level4">
<h4 class="anchored" data-anchor-id="video-navigating-datasets-with-indexing">Video : Navigating Datasets with Indexing</h4>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/js2vV5P4DSQ" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<ul>
<li>Use this video to answer the check-in questions below.</li>
</ul>
</section>
</section>
<section id="check-in-navigating-variables-and-datasets-with-indexing" class="level3">
<h3 class="anchored" data-anchor-id="check-in-navigating-variables-and-datasets-with-indexing"><a href="https://docs.google.com/forms/d/e/1FAIpQLSeYROuiCU1wKb5W36k9IQIKMra2y5Wt9P84Er8WdBaQ6hvHNw/viewform?usp=sf_link">Check-In : Navigating Variables and Datasets with Indexing</a></h3>
<p>Use the fake dataset below and your knowledge of navigating datasets with indexing to identify what answer R would give if you gave it the following code. (Note : no R is needed to complete this problem).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  StudentID favDrink age
1         1     boba  20
2         2     boba  19
3         3     boba  54
4         4   coffee  22
5         5    water  38</code></pre>
</div>
</div>
</section>
</section>
<section id="the-.csv-file" class="level2">
<h2 class="anchored" data-anchor-id="the-.csv-file">The .csv File</h2>
<section id="definition-the-.csv-file" class="level3">
<h3 class="anchored" data-anchor-id="definition-the-.csv-file">Definition : The .csv File</h3>
<p>As a researcher, you will work with data that you (or other researcher friends) have collected. The .csv file (csv stands for comma separated variables) is one of the most common formats for storing data that you will encounter. You’ve probably encountered this before, and likely have opened this file type in a program like excel or google sheets. But in this class, we’ll learn to load these files directly into R. Using R has two advantages :</p>
<ul>
<li>R is way more powerful than excel or Google Sheets.</li>
<li>R allows us to document all of our steps. This semester, we’ll learn how to make changes to the dataset (e.g., changing the names of a variable; removing bad data; transforming data). It’s important to be completely transparent about these changes, and doing these changes in R (with an R Script!) will ensure that we document our steps for our future selves / other researchers.</li>
</ul>
</section>
<section id="videos-how-to-load-datasets-in-r" class="level3">
<h3 class="anchored" data-anchor-id="videos-how-to-load-datasets-in-r">Videos : How to Load Datasets in R</h3>
<p>There are two different ways to load a data file into R : one way (“the point and click method”) involves clicking some boxes, like most of y’all are used to doing. The second way involves typing in an R command. Below are videos that highlight each method.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Regardless of which method you use, there are three things you want to check every time you load data : change the name of the dataset (to make it something simple to type and memorable); check the headers (make sure the variables have names, since sometimes), and set stringAsFactors = TRUE (which will automatically convert all your string variables into categorical factor variables, which is almost always what you will want to do in this class.</p>
<p>These instructions are highlighted because students often forget. So note the importance! They are important steps!!!</p>
</div>
</div>
<section id="video-importing-data-with-the-point-and-click-method-and-console-method" class="level4">
<h4 class="anchored" data-anchor-id="video-importing-data-with-the-point-and-click-method-and-console-method">Video : Importing Data with the “Point and Click” Method and Console Method</h4>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/XLew6OeYAm0" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<ul>
<li>the “point and click” method of loading data</li>
<li>the console / Rscript method of loading data</li>
</ul>
</section>
<section id="video-for-posit-users-working-with-projects-and-loading-data-in-the-cloud." class="level4">
<h4 class="anchored" data-anchor-id="video-for-posit-users-working-with-projects-and-loading-data-in-the-cloud.">Video : For Posit Users : working with projects and loading data in the cloud.</h4>
<p>{{&lt; video https://youtu.be/HOhINtpyjT4&gt; }}</p>
<ul>
<li>posit.cloud users! You will need an extra step that folks using posit.cloud have to use to upload datasets to the cloud (and then import them).</li>
</ul>
</section>
</section>
</section>
</section>
<section id="practice-quiz-2" class="level1">
<h1>Practice Quiz 2</h1>
<p>Okay, this was a LOT. Like drinking water from a fire hose. I promise this will get easier, and it just requires practice. Let’s see how clear the professor’s instructions were with this….Required Practice Quiz!</p>
<p><a href="https://docs.google.com/forms/d/e/1FAIpQLSczCIkUMPcHX36bYbBpU4fH2Ei_U4neGsERl5WD8jTWRSxfiw/viewform?usp=sf_link"><strong>CLICK THIS LINK to take the Practice Quiz.</strong></a> Use your knowledge of navigating and loading datasets to answer&nbsp;</p>
<ul>
<li><p><a href="https://www.dropbox.com/scl/fi/972y9dq8yan2l2q7cme5f/2.1_NavigatingData.R?rlkey=al8gff6iqxj0fdiy0mn8wiyp9&amp;dl=0"><strong>Here’s an Rscript with the practice quiz questions</strong></a><strong>.</strong> Submit your answers to the link above for credit (this is graded based on completion).</p></li>
<li><p><a href="https://youtu.be/cfeogtcAhNM"><strong>Here’s a video key with the practice quiz answers</strong></a><strong>.</strong> Please attempt the quiz on your own; if you get stuck, refer to the relevant videos above. And feel free to reach out on Discord if something’s confusing or I got something wrong. Appreciate y’alls engagement!</p></li>
</ul>
</section>
<section id="tldr" class="level1">
<h1>TLDR</h1>
<p>We learned about different kinds of data (numeric and categorical), and how to graph and interpret these data. We also learned how to load and navigate datasets in R in order to look at variables.</p>
<p>In lecture this week, we will continue to get practice working with datasets and variables. Yeah!</p>
<p>That is all. Thx for reading, as always.</p>
</section>
<section id="chapter-appendix-r-commands" class="level1">
<h1>Chapter Appendix : R Commands</h1>
<section id="r-code-creating-variables-in-r" class="level2">
<h2 class="anchored" data-anchor-id="r-code-creating-variables-in-r">R Code : Creating Variables in R</h2>
</section>
<section id="numeric-variables-in-r" class="level2">
<h2 class="anchored" data-anchor-id="numeric-variables-in-r">Numeric Variables in R</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 73%">
</colgroup>
<thead>
<tr class="header">
<th>Code</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><p><code>variable &lt;- c(#, #, #, #, etc.)</code></p>
<p><code>tired &lt;- c(1,2,3,4)</code></p></td>
<td><p><strong>variable</strong> = an object that you will define in R</p>
<p><strong>&lt;-</strong> = “assign”; tells R to save whatever comes on the right to whatever object is on the left.</p>
<p><strong>c</strong> = combine : tells R to combine whatever happens in the parentheses</p>
<p><strong>()</strong> = parentheses to group related terms</p>
<p><strong># =</strong> what you store in the variable; each item should be separated by a comma and space.</p></td>
</tr>
<tr class="even">
<td><code>hist(dat$variable)</code></td>
<td><strong>For continuous variables :</strong> draws a histogram.</td>
</tr>
</tbody>
</table>
</section>
<section id="string-variables" class="level2">
<h2 class="anchored" data-anchor-id="string-variables">String Variables</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 76%">
</colgroup>
<tbody>
<tr class="odd">
<td><p><code>variable &lt;- c(“name1”, “name2”, “name1”, etc.)</code></p>
<p><code>emotion &lt;- c(“sad”, “happy”, “sad”)</code></p></td>
<td><p><strong>variable</strong> = an object that you will define in R</p>
<p><strong>&lt;-</strong> = “assign”; tells R to save whatever comes on the right to whatever object is on the left.</p>
<p><strong>c</strong> = combine : tells R to combine whatever happens in the parentheses</p>
<p><strong>()</strong> = parentheses to group related terms</p>
<p><strong># =</strong> what you store in the variable; each item should be separated by a comma and space.</p></td>
</tr>
<tr class="even">
<td><p><code>as.factor(variable)</code></p>
<p><code>as.factor(emotion)</code></p></td>
<td><strong>as.factor()</strong> # converts a string variable into a categorical factor</td>
</tr>
<tr class="odd">
<td><code>variable &lt;- as.factor(variable)</code></td>
<td><strong># “</strong>saves” this conversion as the original variable</td>
</tr>
<tr class="even">
<td><code>plot(dat$variable)</code></td>
<td><strong>For categorical variables :</strong> draws a barplot. For continuous variables :&nbsp; illustrates values of the variable (y-axis) as a function of their index (x-axis).</td>
</tr>
</tbody>
</table>
</section>
<section id="r-commands-for-importing-and-navigating-data" class="level2">
<h2 class="anchored" data-anchor-id="r-commands-for-importing-and-navigating-data">R Commands for Importing and Navigating Data</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>R Command</strong></td>
<td><strong>What it Does</strong></td>
</tr>
<tr class="even">
<td><code>dat &lt;- read.csv(“path/file.csv”, stringsAsFactors = T)</code></td>
<td>loads the data file into R (or use the “point &amp; click method”); sets string variables to be categorical factor variables.</td>
</tr>
<tr class="odd">
<td><code>head(dat)</code></td>
<td>looks at the first 6 rows of the data file</td>
</tr>
<tr class="even">
<td><code>tail(dat)</code></td>
<td>looks at the last 6 rows of the data file</td>
</tr>
<tr class="odd">
<td><code>nrow(dat)</code></td>
<td>displays the number of rows (each row = an individual)</td>
</tr>
<tr class="even">
<td><code>ncol(dat)</code></td>
<td>displays the number of columns (each column = a variable)</td>
</tr>
<tr class="odd">
<td><code>names(dat)</code></td>
<td>displays the names of the object (column names = names of variables)</td>
</tr>
<tr class="even">
<td><code>dat$variable</code></td>
<td>displays the variable from a dataset</td>
</tr>
<tr class="odd">
<td><code>dat$variable[i]</code></td>
<td>displays the individual row [i] from the variable</td>
</tr>
<tr class="even">
<td><code>dat[i, j]</code></td>
<td>displays an individual row [i] and column [j] from the dataset</td>
</tr>
</tbody>
</table>
</section>
<section id="r-commands-for-visualizing-data" class="level2">
<h2 class="anchored" data-anchor-id="r-commands-for-visualizing-data">R Commands for Visualizing Data</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>R Command</strong></td>
<td><strong>What it Does</strong></td>
</tr>
<tr class="even">
<td><code>summary(dat)</code></td>
<td>Reports descriptive statistics for all variables in the dataset.</td>
</tr>
<tr class="odd">
<td><code>summary(dat$variable)</code></td>
<td>Reports descriptive statistics for a categorical variable (frequency / number of individuals in each level) or continuous variable (mean, range, etc.)</td>
</tr>
<tr class="even">
<td><code>as.numeric(dat$variable)</code></td>
<td>Makes the variable numeric (for continuous graphs)</td>
</tr>
<tr class="odd">
<td><code>as.factor(dat$variable)</code></td>
<td>Makes the variable a categorical factor (for categorical graphs)</td>
</tr>
<tr class="even">
<td><code>dat$variable &lt;- as.factor(dat$variable)</code></td>
<td>Assigns the as.factor output to the original variable. (In other words, this saves your new categorical factor variable by overwriting the old one.)</td>
</tr>
<tr class="odd">
<td><code>plot(dat$variable)</code></td>
<td>For categorical variables : draws a barplot. For continuous variables :&nbsp; illustrates values of the variable (y-axis) as a function of their index (x-axis).</td>
</tr>
<tr class="even">
<td><code>hist(dat$variable)</code></td>
<td>For continuous variables : draws a histogram.</td>
</tr>
<tr class="odd">
<td><code>par(mfrow = c(i, j))</code></td>
<td>Splits your graphics window into i rows and j columns.</td>
</tr>
</tbody>
</table>


</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>These data come from the hormone_data.csv file, which should be updated to our course page. You’ll learn more about how to access these data files later in this chapter.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>they are all one color - the <em>human color</em>. just kidding from the top left it’s 2, 3, 4, and 7. but I’m blue green color blind so you should argue with me in the comments.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p><a href="https://compass.onlinelibrary.wiley.com/doi/pdfdirect/10.1111/spc3.12506">See this article</a> for research documenting this phenomenon, and arguing why a more inclusive science is needed.</p>
<p><br>
<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p><a href="http://abcnews.go.com/blogs/headlines/2014/02/heres-a-list-of-58-gender-options-for-facebook-users">facebook’s attempt</a> at measuring more complex categories.</p>
<p><br>
<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>a <a href="https://scalar.usc.edu/works/index-2/media/the-gender-spectrum">continuous approach</a> to measuring gender. hi if u still reading, let me know if you have any thoughts on this section of the chapter.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Will learn about these ideas much later this semester! here’s a link to learn more about <a href="https://mba.haas.berkeley.edu/student-life/women">women in Haas</a>. capitalism will eat us all eventually I guess, and good to challenge our stereotypes / perceptions!<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/1R_WhyStats.html" class="pagination-link" aria-label="Why Statistics?">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Why Statistics?</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/3R_Description.html" class="pagination-link" aria-label="Description">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Description</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>