<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Why Statistics? - Sampling Error and Bias</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/10R_NHSTPower.html" rel="next">
<link href="../chapters/8R_Assumptions.html" rel="prev">
<link href=".././images/open_source_mouse.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Why Statistics?</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="http://catterson.github.io/calstats/calstatsSP25.html"> 
<span class="menu-text">Psych 101 [Lecture Notes, Labs, Syllabus]</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../Rcode.html" aria-current="page"> 
<span class="menu-text">List of R Code</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://catterson.github.io"> 
<span class="menu-text">Prof.&nbsp;Cat Homepage</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/9R_SamplingError.html">Predicting Reality</a></li><li class="breadcrumb-item"><a href="../chapters/9R_SamplingError.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Sampling Error and Bias</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="../index.html" class="sidebar-logo-link">
      <img src=".././images/open_source_mouse.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/0R_About.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Describing People</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/1R_WhyStats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Why Statistics?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/2R_Data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/3R_Description.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Description</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/4R_Scales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Measures</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/5R_GoodScience.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Why Research Methods?</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Predicting People</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/6R_LinearModels.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">The Linear Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/7R_CategoricalIV.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Linear Model Pt 2: Categorical IVs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/8R_Assumptions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">More Levels and Experiments</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Predicting Reality</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/9R_SamplingError.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Sampling Error and Bias</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/10R_NHSTPower.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Null Hypothesis Significance Testing and Power</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/11R_MultipleRegression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Multiple Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/12R_Conclusion2Introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Conclusion 2 Introduction</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Rcode.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Rcode</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
    <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="99">
    <h2 id="toc-title">In This Chapter</h2>
   
  <ul>
  <li><a href="#is-this-the-real-life-is-this-just-fantasy-inferential-statistics" id="toc-is-this-the-real-life-is-this-just-fantasy-inferential-statistics" class="nav-link active" data-scroll-target="#is-this-the-real-life-is-this-just-fantasy-inferential-statistics">Is This The Real Life? Is This Just Fantasy? (Inferential Statistics)</a>
  <ul>
  <li><a href="#samples-and-populations" id="toc-samples-and-populations" class="nav-link" data-scroll-target="#samples-and-populations">Samples and Populations</a></li>
  <li><a href="#when-the-sample-doesnt-equal-the-population" id="toc-when-the-sample-doesnt-equal-the-population" class="nav-link" data-scroll-target="#when-the-sample-doesnt-equal-the-population">When the Sample Doesn’t Equal the Population</a></li>
  </ul></li>
  <li><a href="#sampling-bias" id="toc-sampling-bias" class="nav-link" data-scroll-target="#sampling-bias">Sampling Bias</a>
  <ul>
  <li><a href="#evaluating-whether-sampling-bias-exists" id="toc-evaluating-whether-sampling-bias-exists" class="nav-link" data-scroll-target="#evaluating-whether-sampling-bias-exists">Evaluating Whether Sampling Bias Exists</a></li>
  <li><a href="#obama-polling-example-sampling-bias" id="toc-obama-polling-example-sampling-bias" class="nav-link" data-scroll-target="#obama-polling-example-sampling-bias">Obama Polling Example : Sampling Bias</a></li>
  <li><a href="#types-of-sampling-bias" id="toc-types-of-sampling-bias" class="nav-link" data-scroll-target="#types-of-sampling-bias">Types of Sampling Bias</a></li>
  <li><a href="#another-example" id="toc-another-example" class="nav-link" data-scroll-target="#another-example">Another Example</a></li>
  </ul></li>
  <li><a href="#sampling-error-conceptual" id="toc-sampling-error-conceptual" class="nav-link" data-scroll-target="#sampling-error-conceptual">Sampling Error (Conceptual)</a>
  <ul>
  <li><a href="#thinking-through-a-population" id="toc-thinking-through-a-population" class="nav-link" data-scroll-target="#thinking-through-a-population">Thinking Through a Population</a></li>
  <li><a href="#using-r-to-define-a-perfectly-random-sample" id="toc-using-r-to-define-a-perfectly-random-sample" class="nav-link" data-scroll-target="#using-r-to-define-a-perfectly-random-sample">Using R to Define a “Perfectly Random Sample”</a></li>
  <li><a href="#our-perfect-sample-has-error" id="toc-our-perfect-sample-has-error" class="nav-link" data-scroll-target="#our-perfect-sample-has-error">Our “Perfect” Sample Has “Error”</a></li>
  <li><a href="#improving-the-quality-of-these-samples" id="toc-improving-the-quality-of-these-samples" class="nav-link" data-scroll-target="#improving-the-quality-of-these-samples">Improving the Quality of These Samples</a></li>
  <li><a href="#spooky-distribution-of-random-sample-estimates-will-alwasy-be-normally-distributed-and-centered-over-the-population-mean." id="toc-spooky-distribution-of-random-sample-estimates-will-alwasy-be-normally-distributed-and-centered-over-the-population-mean." class="nav-link" data-scroll-target="#spooky-distribution-of-random-sample-estimates-will-alwasy-be-normally-distributed-and-centered-over-the-population-mean."><strong>SPOOKY : Distribution of “Random” Sample Estimates Will Alwasy Be Normally Distributed and Centered Over the Population Mean.</strong></a></li>
  </ul></li>
  <li><a href="#estimating-sampling-error-with-null-hypothesis-significance-testing-nhst" id="toc-estimating-sampling-error-with-null-hypothesis-significance-testing-nhst" class="nav-link" data-scroll-target="#estimating-sampling-error-with-null-hypothesis-significance-testing-nhst">Estimating Sampling Error With Null Hypothesis Significance Testing (NHST)</a>
  <ul>
  <li><a href="#nhst-a-written-explanation" id="toc-nhst-a-written-explanation" class="nav-link" data-scroll-target="#nhst-a-written-explanation">NHST : A Written Explanation</a>
  <ul class="collapse">
  <li><a href="#null-hypothesis-significance-testing-an-assumption-that-the-null-hypothesis-is-true" id="toc-null-hypothesis-significance-testing-an-assumption-that-the-null-hypothesis-is-true" class="nav-link" data-scroll-target="#null-hypothesis-significance-testing-an-assumption-that-the-null-hypothesis-is-true"><strong>Null Hypothesis Significance Testing : An Assumption that the Null Hypothesis is “True”</strong></a></li>
  <li><a href="#the-standard-error-estimating-sampling-error-with-nhst" id="toc-the-standard-error-estimating-sampling-error-with-nhst" class="nav-link" data-scroll-target="#the-standard-error-estimating-sampling-error-with-nhst"><strong>The “Standard Error” : Estimating Sampling Error With NHST</strong></a></li>
  <li><a href="#the-t-value-contextualizing-the-difference-between-your-slope-and-the-null-slope-zero." id="toc-the-t-value-contextualizing-the-difference-between-your-slope-and-the-null-slope-zero." class="nav-link" data-scroll-target="#the-t-value-contextualizing-the-difference-between-your-slope-and-the-null-slope-zero."><strong>The “t-value” : Contextualizing the difference between your slope and the null (slope = zero).</strong></a></li>
  <li><a href="#the-p-value-estimating-the-probability-of-observing-a-t-value-this-large-or-larger-if-the-null-hypothesis-were-true." id="toc-the-p-value-estimating-the-probability-of-observing-a-t-value-this-large-or-larger-if-the-null-hypothesis-were-true." class="nav-link" data-scroll-target="#the-p-value-estimating-the-probability-of-observing-a-t-value-this-large-or-larger-if-the-null-hypothesis-were-true."><strong>The “p-value” : estimating the probability of observing a t-value this large (or larger) if the Null Hypothesis Were “True”.</strong></a></li>
  <li><a href="#a-significant-effect" id="toc-a-significant-effect" class="nav-link" data-scroll-target="#a-significant-effect"><strong>A “Significant” Effect</strong></a></li>
  <li><a href="#the-95-confidence-interval" id="toc-the-95-confidence-interval" class="nav-link" data-scroll-target="#the-95-confidence-interval"><strong>The 95% Confidence Interval</strong></a></li>
  </ul></li>
  <li><a href="#calculating-nhst-in-r-very-easy" id="toc-calculating-nhst-in-r-very-easy" class="nav-link" data-scroll-target="#calculating-nhst-in-r-very-easy">Calculating NHST in R : Very Easy!</a></li>
  <li><a href="#nhst-video-explanation" id="toc-nhst-video-explanation" class="nav-link" data-scroll-target="#nhst-video-explanation">NHST : Video Explanation</a></li>
  </ul></li>
  <li><a href="#check-out-statistical-significance" id="toc-check-out-statistical-significance" class="nav-link" data-scroll-target="#check-out-statistical-significance">Check-Out: Statistical Significance</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/9R_SamplingError.html">Predicting Reality</a></li><li class="breadcrumb-item"><a href="../chapters/9R_SamplingError.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Sampling Error and Bias</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Sampling Error and Bias</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/9_Queen.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
<section id="is-this-the-real-life-is-this-just-fantasy-inferential-statistics" class="level2">
<h2 class="anchored" data-anchor-id="is-this-the-real-life-is-this-just-fantasy-inferential-statistics">Is This The Real Life? Is This Just Fantasy? (Inferential Statistics)</h2>
<section id="samples-and-populations" class="level3">
<h3 class="anchored" data-anchor-id="samples-and-populations">Samples and Populations</h3>
<p>So far, the statistics that we’ve done and described have been focused on <strong>sample data</strong> - the data that a reseracher collects and / or analyzes. For example, when we calculate the mean of a sample, we are reporting the statistic that is closest to all the scores in our sample of data. When we calculate a slope, we are describing how one variable is related to another variable in our sample of data.</p>
<p>Researchers are rarely interested in only their sample, but instead want to learn about a broader <strong>population -</strong> that is, all the individuals who might be relevant to a researcher’s question.</p>
<p>As we will discuss, thinking about who would be the population for a research question, and then identifying who is in the sample, is a critical step for understanding and evaluating the interpretation of the data.</p>
<p>The sample is always clearly defined and reported in the “Methods” section, where researchers describe (in detail) the number (sample size = n) and demographic features of the people they studied.</p>
<p>The population is not often clearly defined or reported, but can be inferred by thinking about all the possible people who could be affected by, or relevant to, the researcher’s question.</p>
<p>Below are a few examples of reserach questions, populations, and the specific samples that researchers studied.</p>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td><strong>Researcher Question</strong></td>
<td><strong>Population</strong></td>
<td><strong>Sample (Example)</strong></td>
</tr>
<tr class="even">
<td>What is the patient’s white blood cell count.</td>
<td>All the blood in a person’s body.</td>
<td>The vial of blood that a phlebotomist collects.</td>
</tr>
<tr class="odd">
<td><a href="https://www.pnas.org/doi/10.1073/pnas.2208661120">Is money related to happiness?</a></td>
<td>Everyone in the world who could be happy and have an income.</td>
<td>“Participants were 33,391 employed adults living in the United States. The median age was 33, the median household income was $85,000/year (25th&nbsp;percentile = $45,000; 75th&nbsp;percentile = $137,500; mean = $106,548; SD = $95,393), 36% were male, and 37% were married.”</td>
</tr>
<tr class="even">
<td>Your final project research question.</td>
<td>Who is in the population?</td>
<td>Who will be in your sample?</td>
</tr>
</tbody>
</table>
</section>
<section id="when-the-sample-doesnt-equal-the-population" class="level3">
<h3 class="anchored" data-anchor-id="when-the-sample-doesnt-equal-the-population">When the Sample Doesn’t Equal the Population</h3>
<p>Researchers rarely, if ever, have access to the full population of data, and thus must use the sample to make a guess (or <strong>inference</strong>) about the population. For example, doctors don’t drain a person of all their blood in order to learn about the person’s health, but trust that the sample will give them valid information about what’s going on in the whole body. That’s not always the case, however, and an important task for researchers is to consider the possibility that they are wrong.</p>
<p>The key question is then, how can we trust that the information we learn from the sample is at all related to the broader population? This is hard to do, and the focus of this chapter. In fact, there are two reasons why we would expect that the sample will not, in fact, equal the population.</p>
<p><strong>Sampling Error</strong> describes when the sample is different from the population because of random reasons. A good sample will be random sample, meaning that each individual in the population has an equal chance of being selected for the sample. Even if this is the case, there’s always going to be some differences between the individuals in the study, and the individuals in the population. As you’ll learn in the section below, researchers use statistics to try and estimate how much sampling error might influence their results, and try to design studies to limit the extent that sampling error can affect their results.</p>
<p><strong>Sampling Bias</strong> describes when the sample is different from the population because of predictable (or non-random) reasons. A blood sample would be biased if we knew there was something systematically different about the blood that was drawn from the arm vs.&nbsp;the hand vs.&nbsp;the neck vs.&nbsp;the part of your foot between your toes. Identifying sampling bias requires some critical thinking skills that we will practice in the section below, and our goal as researchers will be to identify possible sources of bias, and minimize their influence (or do new studies to test their influence.)</p>
<p>Let’s start with sampling bias, because it’s a lot shorter and easier to understand :)</p>
</section>
</section>
<section id="sampling-bias" class="level2">
<h2 class="anchored" data-anchor-id="sampling-bias">Sampling Bias</h2>
<section id="evaluating-whether-sampling-bias-exists" class="level3">
<h3 class="anchored" data-anchor-id="evaluating-whether-sampling-bias-exists">Evaluating Whether Sampling Bias Exists</h3>
<p>There are three questions to consider when evaluating whether sampling bias is influencing the results.</p>
<ol type="1">
<li><strong>What is the research question, who is the population relevant to this question, and who is in the sample?</strong> This first question (…okay, technically three questions) asks you to define the key features of the study (as described above.)</li>
<li><strong>Is the sample representative of the population, or is there a systematic bias?</strong> The second question asks you to evaluate whether the people in the sample are predictably different from the people in the population. This will almost always be true - most psychological research questions are relevant to people across the world, and it’s very difficult to ensure that everyone in the world has an equal chance of participating in the study.</li>
<li><strong>Is this bias related to the dependent variable? (Will the bias influence the results?)</strong> The final question is the hardest, and most important, to consider.</li>
</ol>
</section>
<section id="obama-polling-example-sampling-bias" class="level3">
<h3 class="anchored" data-anchor-id="obama-polling-example-sampling-bias">Obama Polling Example : Sampling Bias</h3>
<p>Below are data from 2012<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>, when Barack Obama was running against Mitt Romney in the US Presidential Election. Look over the data, and think about the answers to the three questions to evaluate sampling bias.</p>
<p><img src="images/clipboard-3670391903.png" class="img-fluid"></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<strong>What is the research question, who is the population relevant to this question, and who is in the sample?</strong>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li><p><strong>the question :</strong> who are people going to vote for US President in 2012?</p></li>
<li><p><strong>the population :</strong> all voters / likely voters in the US.</p></li>
<li><p><strong>there are multiple samples :</strong> some polls only sample people without cell-phones by randomly calling people who have landline phones. other polls sample people with landlines or cell-phones.</p></li>
</ul>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<strong>Is the sample representative of the population, or is there a systematic bias?</strong>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li><strong>no!</strong> the sample is not representative of the population. not all voters have landline phones (or cell-phones, but more folks have cell-phones these days). So while both samples are biased, the samples that only include landline phone owners are more biased than the samples that include both landlines and cell-phone owners.</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Is this bias <strong>related</strong> to the <strong>dependent variable</strong>? (Will the bias influence the results?)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li><p>the bias is related to the dependent variable / research question. landline phone owners will tend to be older, and older voters tend to vote more conservative.</p></li>
<li><p>You can see this bias in the data; Obama (the more liberal candidate) was predicted to win by less in the studies that only sampled landline phone owners.</p></li>
</ul>
</div>
</div>
</div>
</section>
<section id="types-of-sampling-bias" class="level3">
<h3 class="anchored" data-anchor-id="types-of-sampling-bias">Types of Sampling Bias</h3>
<p>The sampling bais in this example would be labeled <strong>exclusion bias;</strong> below are a few other common types of biases.</p>
<ul>
<li><strong>Self-Selection Bias :</strong> People volunteer to be in a study, and there’s likely something different about someone who might choose to be in a study compared to someone who may not want to be in a study in ways that might influence the results.</li>
<li><strong>Survivor Bias :</strong> Participants often drop out of a study, especially those where you are following the participant over a long period of time. Researchers therefore are only collecting data from a specific group of people who “lasted” through the study. I experience this with my check-ins; the students who rate how the class is going are biased, because they are the ones who haven’t quit out of boredom or anxiety.</li>
<li><strong>WEIRD Samples.</strong> Read the short article <a href="https://www.dropbox.com/s/p9rszc3afaiwmcs/2010_WEIRDinScience.pdf?dl=0">“A WEIRD View of Human Nature”</a> that describes how most psychologists get samples for their studies. Focus on the following key ideas: the definition of WEIRD; the frequency and influence of cross-cultural research on sampling biases.</li>
</ul>
</section>
<section id="another-example" class="level3">
<h3 class="anchored" data-anchor-id="another-example">Another Example</h3>
<ol type="1">
<li><p>What is the POPULATION for “Rate My Professor” (a website where students rate the quality of a professor they have had)?</p>
<ol type="1">
<li><p>All the people in the world.</p></li>
<li><p>All the students in the world.</p></li>
<li><p>All the students who have taken a specific professor’s course.</p></li>
<li><p>All the students who wrote a review about the course.</p></li>
<li><p>All the students who read the reviews.</p></li>
</ol></li>
<li><p>What is the SAMPLE for “Rate My Professor” (a website where students rate the quality of a professor they have had)?</p>
<ol type="1">
<li><p>All the people in the world.</p></li>
<li><p>All the students in the world.</p></li>
<li><p>All the students who have taken a specific professor’s course.</p></li>
<li><p>All the students who wrote a review about the professor’s course.</p></li>
<li><p>All the students who read the reviews.</p></li>
</ol></li>
<li><p>What does WEIRD stand for?</p>
<ol type="1">
<li><p>White, Educated, Individualistic, Rich, Democratic</p></li>
<li><p>Western, Educated, Industrial, Rich, Democratic</p></li>
<li><p>A statistical term that describes participants who are more than three standard deviations from the average of a variable.</p></li>
<li><p>This is a term that psychologists no longer use because it is dehumanizing</p></li>
<li><p>None of the above.</p></li>
</ol></li>
<li><p>According to the article on cross-cultural differences in psychology…</p>
<ol type="1">
<li><p>Effects that are “fundamental” do not differ across cultures.</p></li>
<li><p>Certain areas of psychology, like visual perception, do not differ across cultures.</p></li>
<li><p>Most psychological researchers put effort into examining cross-cultural differences.</p></li>
<li><p>All of the above.</p></li>
<li><p>None of the above.</p></li>
</ol></li>
<li><p>Dr.&nbsp;Researcher wants to study people’s attitudes about marijuana. According to the Professor’s video in the reading notes, which of the following would be an example of sampling bias?</p>
<ol type="1">
<li><p>Dr.&nbsp;Researcher surveys people living in the Bay Area (where people tend to have more positive attitudes about marijuana than people living in other places).</p></li>
<li><p>Dr.&nbsp;Researcher surveys people living in Lytle, Texas (where people tend to have more negative attitudes about marijuana than people living in other places).</p></li>
<li><p>Dr.&nbsp;Researcher surveys people wearing white t-shirts (a factor that is unrelated to attitudes about marijuana).</p></li>
<li><p>Both A and B</p></li>
<li><p>all of the above.</p></li>
</ol></li>
</ol>
<p>&nbsp;Piff, P. K., Dietze, P., Feinberg, M., Stancato, D. M., &amp; Keltner, D. (2015). Awe, the small self, and prosocial behavior. Journal of personality and social psychology, 108(6), 883. <a href="https://bpb-us-e1.wpmucdn.com/sites.gatech.edu/dist/c/359/files/2018/08/Awe-and-Prosocial-Behavior.pdf?bid=359">LINK TO FULL ARTICLE</a></p>
<p><br>
</p>
<p><img src="images/clipboard-3582987792.png" class="img-fluid"></p>
</section>
</section>
<section id="sampling-error-conceptual" class="level2">
<h2 class="anchored" data-anchor-id="sampling-error-conceptual">Sampling Error (Conceptual)</h2>
<section id="thinking-through-a-population" class="level3">
<h3 class="anchored" data-anchor-id="thinking-through-a-population">Thinking Through a Population</h3>
<p>Okay, this may seem a little strange, but I’ll need your full attention for this part of the chapter. Please place your left and right hand thumbs and index fingers together to make a triangle with your two hands. Spread your other fingers forward, so you are using your full hand to make this power triangle.</p>
<p><img src="images/IMG_1263.jpg" class="img-fluid"></p>
<p>Okay, now please place your thumbs in between your eyebrows, and stare at the triangle below. While you stare, say “na-na-na-na-na-na-na-na-na-na” (repeating) - starting as quiet as you can, and getting as loud as you feel comfortable for no less than 5 seconds and no more than 15 seconds. I’ll give you a moment to do this.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/9_triangle.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
<p>Wow. Did you feel that power? You did, right?? Yeah. Amazing.</p>
<p>What we’ve done - through the power of triangles (the strongest shape, both physically and psychologically) - is generate a dataset<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> that we will consider to be a population of data.</p>
<p>I’ve named this dataset babby, and it has two variables for 40000 individuals - one IV and one DV.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>babby <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"~/Dropbox/Teaching Datasets/brainwavebabydata.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(babby)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           IV         DV
1 -0.72974695  0.7393607
2  1.55894120 -0.8977654
3  1.87894858 -0.4780742
4  0.36830861 -0.9365583
5  0.02805939  1.5690341
6  2.18060600 -2.1974925</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(babby)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 40000</code></pre>
</div>
</div>
<p>If we graph these variables, we see that they appear to each be normally distributed.&nbsp;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(babby<span class="sc">$</span>IV, <span class="at">col =</span> <span class="st">'black'</span>, <span class="at">bor =</span> <span class="st">'white'</span>, <span class="at">main =</span> <span class="st">"Histogram of IV"</span>, <span class="at">xlab =</span> <span class="st">"Independent Variable"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(babby<span class="sc">$</span>DV, <span class="at">col =</span> <span class="st">'black'</span>, <span class="at">bor =</span> <span class="st">'white'</span>, <span class="at">main =</span> <span class="st">"Histogram of DV"</span>, <span class="at">xlab =</span> <span class="st">"Dependent Variable"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="9R_SamplingError_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>And if we plot the relationship between these two variables, we find that there is no relationship between the DV and the IV. Content warning - some students find the image below existentially terrifying. (What do you see in the graph below? What does this say about you and your personality?)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(DV <span class="sc">~</span> IV, <span class="at">data =</span> babby, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">main =</span> <span class="st">"Relationship Between DV and IV"</span>, <span class="at">xlab =</span> <span class="st">"IV"</span>, <span class="at">ylab =</span> <span class="st">"DV"</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(DV <span class="sc">~</span> IV, <span class="at">data =</span> babby)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(mod, <span class="at">lwd =</span> <span class="dv">5</span>, <span class="at">col =</span> <span class="st">'red'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="9R_SamplingError_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>R confirms that there is no relationship between these two variables - the slope for the IV rounds (to ten decimal places) to zero.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)            IV 
-1.110223e-18 -6.306146e-16 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">coef</span>(mod), <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)          IV 
          0           0 </code></pre>
</div>
</div>
<p><br>
So to recap, we have a population of data (40,000 individuals) for whom the “true” relationship is zero.<br>
<br>
</p>
</section>
<section id="using-r-to-define-a-perfectly-random-sample" class="level3">
<h3 class="anchored" data-anchor-id="using-r-to-define-a-perfectly-random-sample">Using R to Define a “Perfectly Random Sample”</h3>
<p>As described above, psychologists will almost never have access to the true population of data. Instead, they take a “sample” from the population. When every individual in the population has an equal chance of being selected for this sample, we can say the sample is a “random sample”. When there are certain individuals who are more or less likely to be included in the sample, we say the sample has “bias”.</p>
<p>Most samples in psychology are biased; taking a random sample from the population as a psychological researcher is incredibly difficult, if not impossible. However, even if you were to take a perfectly random sample from the population, you should expect your sample to differ at least a little from the broader population.</p>
<p>We can illustrate this in R. R has a built-in function called sample(), which takes a random sample<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> of whatever numbers you give it. For example, here’s a fun game - think of a number between 1 and 10. Then ask R to sample() a random number between 1 and 10 and see if you are vibing with R. I am thinking of the number FOUR.</p>
<p>In the code below, I’m asking R to define the numbers 1 through 10, and then draw ONE number from this set.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<p>R chose the number 1. We are not vibing. But every time I run the <code>sample()</code> function again, I’ll get a new random number every time.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4</code></pre>
</div>
</div>
<p>Okay, go ahead and try this yourself - think of a number, and let us know on Discord how many times it took you to run the <code>sample(1:10, 1)</code> function before R chose your number. (Or not.)</p>
<p>We can use this function to ask R to take a “perfect” random sample from our population. I’m going to adapt the code a bit to draw a random sample from the babby dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>babby[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(babby), <span class="dv">10</span>), ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               IV           DV
8826   0.98527631 -0.518293954
16740 -0.55196783  0.056675257
7700   1.10483168  0.005026792
36722  0.09618142  0.117929657
9091  -0.07852571 -0.552495893
33700 -1.00134328  1.441827817
13610 -1.33371387 -1.064411326
28559  0.18542185 -0.461931331
22725  0.47526546 -0.617396883
11224  0.73776812 -2.402637937</code></pre>
</div>
</div>
<ul>
<li><p><strong>babby[ , ] #</strong> this code indexes the babby dataset. the dataset is two dimensional; I can instruct R to select specific rows before the comma, and columns after the comma.</p></li>
<li><p><strong>sample(1:nrow(babby), 10) #</strong> this code instructs R to select specific rows (since it comes before the comma), and tells R to take a random sample of 10 numbers, starting with the number 1 and going through however many rows babby has (in this case, 40,000).&nbsp;&nbsp;</p></li>
<li><p><strong>after the comma,</strong> I have no code, which tells R to give me all the columns (in this case two - the IV and DV)</p></li>
</ul>
<p>As you can see in the above output, R has drawn a random sample of 10 individuals from the list of 40,000. If I run this code again, R will select another 10 individuals from the list of 40,000.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>babby[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(babby), <span class="dv">10</span>), ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               IV          DV
33713  0.08619728  1.63778479
37126 -0.42197038 -0.65012382
12418 -0.38048978  0.61041238
15765 -2.07429669 -0.89532671
9207   0.54379840 -0.02403073
31418 -1.52499812  1.27384500
24609  0.81390193 -0.56375600
103   -0.29130008 -1.44600496
10349  0.17771080 -1.27641647
36940 -0.46201091 -0.67224917</code></pre>
</div>
</div>
<p>If I want to SAVE this sample (and use it later), I need to give it a name so R remembers what the sample is (and doesn’t keep creating new samples).&nbsp;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>sampy <span class="ot">&lt;-</span> babby[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(babby), <span class="dv">10</span>), ]</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>sampy</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              IV         DV
5897   0.8485550 -0.2524885
20003  0.6540785 -0.1779805
16     0.4508883  0.2223145
33756  1.2866107  0.6269824
14232 -1.0166493  0.3983281
25490  1.3144997 -0.7714008
149    0.9310813 -1.3942383
29671  0.3357943  0.4989499
35218  0.5225263 -1.7209132
23309  0.8328597  1.2089172</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>sampy</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              IV         DV
5897   0.8485550 -0.2524885
20003  0.6540785 -0.1779805
16     0.4508883  0.2223145
33756  1.2866107  0.6269824
14232 -1.0166493  0.3983281
25490  1.3144997 -0.7714008
149    0.9310813 -1.3942383
29671  0.3357943  0.4989499
35218  0.5225263 -1.7209132
23309  0.8328597  1.2089172</code></pre>
</div>
</div>
</section>
<section id="our-perfect-sample-has-error" class="level3">
<h3 class="anchored" data-anchor-id="our-perfect-sample-has-error">Our “Perfect” Sample Has “Error”</h3>
<p>Okay, we finally have a perfectly random sample of the population - sampy. If we were researchers, we would use this sample to learn something about what the population is like and, like before, define a linear model to examine the relationship between the DV and IV.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(DV <span class="sc">~</span> IV, <span class="at">data =</span> sampy, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">main =</span> <span class="st">"Relationship Between DV and IV in SAMPY"</span>, <span class="at">xlab =</span> <span class="st">"IV (from sampy)"</span>, <span class="at">ylab =</span> <span class="st">"DV (from Sampy)"</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>modS <span class="ot">&lt;-</span> <span class="fu">lm</span>(DV <span class="sc">~</span> IV, <span class="at">data =</span> sampy)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(modS, <span class="at">lwd =</span> <span class="dv">5</span>, <span class="at">col =</span> <span class="st">'green'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="9R_SamplingError_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">coef</span>(modS), <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)          IV 
    0.02525    -0.26201 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modS)<span class="sc">$</span>r.squared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.03484331</code></pre>
</div>
</div>
<p>Our sample has error - it is not showing us the true nature of the population.<br>
</p>
<p>Indeed, we could ask R to generate 10 random samples of 10 individuals, and see these errors repeat.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">5</span>))</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>)){</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  sampy <span class="ot">&lt;-</span> babby[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(babby), <span class="dv">10</span>), ]</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(DV <span class="sc">~</span> IV, <span class="at">data =</span> sampy, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">main =</span> <span class="st">"Another Sampy"</span>, <span class="at">xlab =</span> <span class="st">"IV"</span>, <span class="at">ylab =</span> <span class="st">"DV"</span>)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  modS <span class="ot">&lt;-</span> <span class="fu">lm</span>(DV <span class="sc">~</span> IV, <span class="at">data =</span> sampy)</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">abline</span>(modS, <span class="at">lwd =</span> <span class="dv">5</span>, <span class="at">col =</span> <span class="st">'green'</span>)</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="9R_SamplingError_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="9R_SamplingError_files/figure-html/unnamed-chunk-11-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(modS)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)          IV 
 0.69109563 -0.02107053 </code></pre>
</div>
</div>
<p>In none of these samples does the slope equal exactly zero - which as we know is the “true” slope of our population. Some may be close, but none are exact - they all have some degree of error. Sampling error. (Whoa.)<br>
</p>
</section>
<section id="improving-the-quality-of-these-samples" class="level3">
<h3 class="anchored" data-anchor-id="improving-the-quality-of-these-samples">Improving the Quality of These Samples</h3>
<p>“But wait, Professor…” I can hear you scream in your mind (actively engaged while reading this text), “these are not very good samples! The sample size was only 10! We can get a better estimate of the population if we survey more people!”</p>
<p>Yes, my dear actively engaged student, you are correct. And yet, there will still be sampling error. We can increase the size of the random sample that R takes by changing the code to define sampy such that it is a random sample of 150 individuals from babby : <code>sampy &lt;- babby[sample(1:nrow(babby), 150), ]</code></p>
<p>Here are 10 more linear models from 10 random samples of babby, each with a sample size of 150<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a>.&nbsp;</p>
<p>What do you notice when looking at these different linear models?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Random Samples: n = 150</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">5</span>))</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>)){</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  sampy <span class="ot">&lt;-</span> babby[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(babby), <span class="dv">150</span>), ]</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(DV <span class="sc">~</span> IV, <span class="at">data =</span> sampy, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">main =</span> <span class="st">"Big Sampy"</span>, <span class="at">xlab =</span> <span class="st">"IV"</span>, <span class="at">ylab =</span> <span class="st">"DV"</span>)</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>  modS <span class="ot">&lt;-</span> <span class="fu">lm</span>(DV <span class="sc">~</span> IV, <span class="at">data =</span> sampy)</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">abline</span>(modS, <span class="at">lwd =</span> <span class="dv">5</span>, <span class="at">col =</span> <span class="st">'green'</span>)</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>  <span class="co">#print(coef(modS))</span></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>  <span class="co">#print(summary(modS)$r.squared)</span></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="9R_SamplingError_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="9R_SamplingError_files/figure-html/unnamed-chunk-12-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>I notice a few things :</strong></p>
<ol type="1">
<li><p><strong>Each sample, as instructed, has 150 individuals in the dataset.</strong> I can see there are more dots in each scatterplot. Good to know that R did what I asked.</p></li>
<li><p><strong>None of the lines appear to have a slope of exactly zero, like our population does.</strong> A few are close (the third linear model on the top row has a slope = 0.003 and an R2 = 0.000011 - close to zero but not exaclty zero! there is still some error!!!)</p></li>
<li><p><strong>I can see that there’s less variation in the steepness of the lines.</strong> Some slopes (like top row fourth column) appear steeper than others, but I see less extremes in the variation in these slopes when I have a sample size = 150 than when I have a sample size = 10. (I can see this because the green lines are more similar to each other when n = 150 than when n = 10.)</p></li>
</ol>
<p><strong>This last point is a critical idea : we can “visualize” sampling error by thinking about how much the slopes from multiple samples differ from each other.</strong></p>
<ul>
<li><p>A small amount of sampling error would mean that each sample is very similar to the “truth” of our population. If sampling error is small, we’d expect to see very little variation in our slopes across different samples.&nbsp;</p></li>
<li><p>A large amount of sampling error would mean that each sample is VERY DIFFERENT from the “truth” of our population. If sampling error is large, we’d expect to see a lot of variation in our slopes across different samples.</p></li>
</ul>
<p>Below, I illustrate sampling error by asking R to take a random sample from my population (where the “true” slope = 0), save the value of the slope from this sample, and then repeat this process 1000 times.</p>
<p>The graphs below show histograms of these 1000 slopes for a sample size of n = 10 (on the left) and n = 150 (on the right). I’ll walk through the graphs below in more detail, but at first glance you can hopefully see that there’s less variation in our slopes when the sample size is 150 than when the sample size is 10.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="9R_SamplingError_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>The graph on the left reports the slopes of 1000 samples when the sample size = 10.</strong></td>
<td><strong>The graph on the right reports the slopes of 1000 samples when the sample size = 150.</strong></td>
</tr>
<tr class="even">
<td><ul>
<li><p>The range of these random samples (n = 10) was between -1.56 and 1.46.</p></li>
<li><p>The standard deviation of these 1000 slopes is .37, which tells us that the “average” random sample differs from the mean by about .37.</p></li>
<li><p>The mean of these 1000 slopes is zero (which is the “true” population mean!!!).</p></li>
</ul></td>
<td><ul>
<li><p>The range of these random samples (n = 150) was between -0.24 and 0.26.</p></li>
<li><p>The standard deviation of these 1000 slopes is .08, which tells us that the “average” random sample differs from the mean by about .08.</p></li>
<li><p>The mean of these 1000 slopes is zero (which is the “true” population mean!!!)</p></li>
</ul></td>
</tr>
</tbody>
</table>
</section>
<section id="spooky-distribution-of-random-sample-estimates-will-alwasy-be-normally-distributed-and-centered-over-the-population-mean." class="level3">
<h3 class="anchored" data-anchor-id="spooky-distribution-of-random-sample-estimates-will-alwasy-be-normally-distributed-and-centered-over-the-population-mean."><strong>SPOOKY : Distribution of “Random” Sample Estimates Will Alwasy Be Normally Distributed and Centered Over the Population Mean.</strong></h3>
<p>When taking a random sample from the population, we always expect to see a “normal” / symmetrical distribution that is centered over the mean of the population. (This is called the Central Limit Theorem.)</p>
<p>The distribution of sample estimates (what happens to the slope if we ask R to take a random sample of the population) will always be normally distributed, since a) each estimate is determined by multiple individuals (“There are multiple explanations for why the variation occurs (life is complex!)” and b)“these multiple explanations occur randomly” (since R is using very good randomization techniques.)&nbsp;</p>
<p><strong>TLDR : IF we are drawing random samples from a population, we can expect that the distribution of estimates from multiple samples (the many slopes that we find) will be normally distributed. We care about this because if we can predict what random sampling will look like, it will allow us to estimate the amount of variation caused by random sampling error. And we can then build that estimate of sampling error into our model, and try to estimate how “wrong” our sample might be. To be clear, all of this is made up - a replication is the best thing to do if you really want to know whether your sample is representative of the population. But replications can be expensive in terms of time and money, and the “publish or perish” beast must be fed.</strong></p>
<p>In the next part, you’ll learn about a very common way researchers try to estimate sampling error.</p>
</section>
</section>
<section id="estimating-sampling-error-with-null-hypothesis-significance-testing-nhst" class="level2">
<h2 class="anchored" data-anchor-id="estimating-sampling-error-with-null-hypothesis-significance-testing-nhst">Estimating Sampling Error With Null Hypothesis Significance Testing (NHST)</h2>
<p>The goal of NHST is to estimate how much sampling error might be influencing the results. Again - we are making things up here - without repeatedly taking samples from the data, we don’t actually know how much sampling error might be influencing the results. But in theory, it’s better to have an estimate of sampling error (even if it’s wrong) than just pretend that our sample is THE TRUTH™.</p>
<section id="nhst-a-written-explanation" class="level3">
<h3 class="anchored" data-anchor-id="nhst-a-written-explanation">NHST : A Written Explanation</h3>
<section id="null-hypothesis-significance-testing-an-assumption-that-the-null-hypothesis-is-true" class="level4">
<h4 class="anchored" data-anchor-id="null-hypothesis-significance-testing-an-assumption-that-the-null-hypothesis-is-true"><strong>Null Hypothesis Significance Testing : An Assumption that the Null Hypothesis is “True”</strong></h4>
<p>Null Hypothesis Significance Testing (NHST) starts with the assumption that the null hypothesis is “true”. You can remember this important detail by noting the phrase starts with “Null Hypothesis”.</p>
<p>If the null hypothesis is “true”, then you would not expect to find a relationship between the two variables (since researchers’ theory - the alternative hypothesis - is often predicting that some relationship between two variables exists).&nbsp;</p>
<p>In other words, if the null hypothesis were true, you’d expect to find a slope of zero - no relationship.</p>
<p><strong>If you DID NOT find a slope of zero in your study, then there are two possibilities :</strong></p>
<ol type="1">
<li><p>Your study found a real relationship between two variables - the null hypothesis is NOT TRUE.</p></li>
<li><p>Your study experienced some sampling error - the null hypothesis IS TRUE, but you drew a random sample from the population that made it seem like there’s a relationship between these two variables.&nbsp;</p></li>
</ol>
<p>In order to evaluate whether the non-zero slope you found is due to 1) some real relationship between the two variables or 2) sampling error, you need to determine how much sampling error might be influencing your results.&nbsp;</p>
<p>Many replications would be the best way to do this. As discussed, replications are costly in terms of time and money (paying for participants, grad student salaries, fMRI machine time, etc.)</p>
<p>So researchers have developed methods of estimating sampling error. One method is described below.</p>
</section>
<section id="the-standard-error-estimating-sampling-error-with-nhst" class="level4">
<h4 class="anchored" data-anchor-id="the-standard-error-estimating-sampling-error-with-nhst"><strong>The “Standard Error” : Estimating Sampling Error With NHST</strong></h4>
<p>The “Standard Error” is the name given to the NHST approach to estimating sampling error. The “conceptual” equation<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> to estimate standard error is as follows :</p>
<p><span class="math display">\[
\huge \text{standard error (SE)} = \frac{\sigma}{\sqrt{n}}
\]</span></p>
<p>Remember that <span class="math inline">\(\sigma\)</span> is the standard deviation and <span class="math inline">\(n\)</span> is the sample size. Based on this equation, you can determine that the standard error will increase as the standard deviation increases, or when the sample size decreases. Remember that standard error is an estimate of sampling error; you can think of the standard error like standard deviation. However, whereas standard deviation describes how much the average individual score differs from the mean, the standard error estimates how much the average individual samples might differ from the estimated slope (the slope you found in your study). Again, we are making this up - we don’t know what the sampling error actually will be, or whether the estimate from our sample is a good estimate of the population. But it’s all we have.</p>
<p>So we expect that we will have MORE sampling error when :&nbsp;</p>
<ol type="1">
<li><p><strong>….our standard deviation increases.</strong> A larger standard deviation means that individuals are very different from each other (individual scores differ a lot from the mean). If individuals differ a lot from each other, than which individuals are in our sample will matter more (and create more sampling error) than if everyone was the same. Imagine doing a study of robots who are all programmed to give the same answer - I could study one robot, and probably learn about ALL the robots.</p></li>
<li><p><strong>….our sample size decreases.</strong> The more people we have in our study, the smaller we expect sampling error to be. We saw this when we took larger sample sizes of babby. Asking two students what they think of these notes will give me more error than if I ask half the class, or even better, the entire class.</p></li>
</ol>
<p><strong>To be clear - our estimate of sampling error is ENTIRELY MADE UP.</strong> We do not actually know how much sampling error there is in our study - we would need to do multiple replications in order to determine this, which would be costly in terms of time and money. So the standard error is a GUESS about sampling error, and a way to help us better understand the slope that we found.<br>
<br>
<strong>As a pretend example.</strong> Let’s say I’m a researcher who found a slope of .50 with a sample size of 200 and a pooled standard deviation of 2.83. My estimate of sampling error would be .2, which would mean that if the null hypothesis were true, I’d draw a random sample that would (on average) have a slope of .2 or -.2 (even though the “true” slope was zero).</p>
</section>
<section id="the-t-value-contextualizing-the-difference-between-your-slope-and-the-null-slope-zero." class="level4">
<h4 class="anchored" data-anchor-id="the-t-value-contextualizing-the-difference-between-your-slope-and-the-null-slope-zero."><strong>The “t-value” : Contextualizing the difference between your slope and the null (slope = zero).</strong></h4>
<p>Now that we have our estimate of sampling error (the standard error), we want to compare this value to something. Is this sampling error a lot? A little? We can compare this sampling error to the slope that we found. This comparison is called the t-value, and the equation is below :&nbsp;</p>
<p><span class="math display">\[
\huge t = \frac{b}{SE}
\]</span></p>
<p>All the t-value does is evaluate how large the slope from your study (b = the slope) is, compared to the “average” slope you might find due to random sampling error (se = the standard error).&nbsp;</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Pop Quiz. As a researcher hoping to show that your slope is “real”, would you want the t-value to be LARGE or SMALL?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>You would want the t-value to be LARGE, since this means that your slope is a lot bigger than the “average slope” you might find due to sampling error if the null hypothesis were true (the standard error).</p>
</div>
</div>
</div>
<p>The standard error is critical for evaluating the size of your slope. A researcher could find a very large slope - let’s say a correlation of r = .6. But if the researcher finds that the sampling error is also high (r = .6), then the slope they found could easily be found due to chance random sampling from a population where the true slope is equal to zero. In other words, the standard error helps researchers evaluate whether the slope they found is different enough from the average sampling error they might find if they were taking samples from a population where the slope was zero.</p>
<p><strong>As a pretend example :</strong> let’s say that I’m a researcher who found a slope of .5, with a standard error of .2. My t-value would be .5 / .2 = 2.5 = my slope is 2.5 times as large as the average slope I might find due to random sampling if the null hypothesis were true.</p>
</section>
<section id="the-p-value-estimating-the-probability-of-observing-a-t-value-this-large-or-larger-if-the-null-hypothesis-were-true." class="level4">
<h4 class="anchored" data-anchor-id="the-p-value-estimating-the-probability-of-observing-a-t-value-this-large-or-larger-if-the-null-hypothesis-were-true."><strong>The “p-value” : estimating the probability of observing a t-value this large (or larger) if the Null Hypothesis Were “True”.</strong></h4>
<p>The Central Limit Theorem (see above) allows us to expect that our random samples from the population will be normally distributed. As a reminder, the normal distribution describes a range of possible scores that differ from the mean, and assigns a probability to these scores. For example, we can use the chart below to estimate that 50% of the scores will be above the mean, that 13.59 + 2.14 + .13% = 15.86% of scores will be above 1 standard deviation, that 64.26% of scores will be between -1 and +1 standard deviations of the mean, that .13% of scores will be below 4 standard deviations of the mean, and so on.</p>
<p>Note that the graph below reports percentages. But it is also common to report these numbers as percentiles. So a 34.13% would be written as a percentile as .3413.<br>
<br>
<img src="images/clipboard-2984749291.png" class="img-fluid"></p>
<p><strong>The p-value, then, describes the probability that you would observe a t-value as large (or larger) than the one that you observed if the null hypothesis were true.</strong> Practically, the p-value is the percentage of scores that fall further away from the mean from your t-value. A few examples, using the chart above&nbsp; :</p>
<ul>
<li><p>A t-value of -3 would have a p-value of .0013, which means that there is a .13% chance that you would observe a t-value of -3 or more extreme if the null hypothesis were true.</p></li>
<li><p>A t-value of -1 would mean that our slope is as large as the sampling error that we found (the negative sign just means that our slope is negative), and would have a p-value of .1586. This means that we would expect 15.86% of random samples to be as large (or larger) than the slope that we found.&nbsp;</p></li>
<li><p>A t-value of +2 means that our slope is twice as large as the sampling error that we found, and would have a p-value of .0227, which means that we would expect 2.27% of random samples to be as large (or larger) than the slope that we found.&nbsp;</p></li>
</ul>
<p>When R reports the p-value, it’s actually calculating the p-value for both sides of the distribution. That is, if your slope had a t-value of 3-standard errors below the mean, R would report a p-value of .026 or 2.6%, since it’s calculating the probability of the curve that falls to the left of 3 standard deviations below the mean, and also the probability of the curve that falls to the right of 3 standard deviations above the mean.</p>
<p>This is called a two-tailed test, and the logic of doing this by default is :&nbsp;</p>
<ol type="1">
<li><p>If we are really pretending to live in the world of the null hypothesis, then the slope we found in our sample is random. And if it’s random, we could have found a slope this extreme in either the positive OR negative direction. So when estimating the probability of this “random” slope occurring, it’s good to&nbsp;</p></li>
<li><p>A two-tailed test is more conservative, since you are doubling the p-value which increases the probability you report of finding a random slope due to chance. It’s good practice to be more conservative when reporting statistics, since people are biased to find results in their favor.&nbsp;</p></li>
</ol>
<p>Some researchers report a one-tailed test - in R, you would just divide the reported p-value in R in half. The logic in doing this is that researchers claim if they have a strong prediction that their result will be positive (or negative) in direction, they can ignore the other side of the distribution. This has never made sense to me, since NHST is about random sampling (and not the alternative hypothesis) and I’m always a little suspicious of doing things that make it easier to show your hypothesis was supported.</p>
<p><br>
<strong>Back to my pretend example :</strong> with a slope of .5, a standard error of .2, and a t-value of 2.5, R would report my p-value (two sided test) to be p = 0.0132. This means there is a 1.3% chance that I would observe a slope as different from zero as .5 (in either a positive or negative direction) due to random sampling error if the null hypothesis were true. This is a low probability! It is unlikely to happen due to random chance (if the null hypothesis were true). And I could say that it was a significant effect.</p>
</section>
<section id="a-significant-effect" class="level4">
<h4 class="anchored" data-anchor-id="a-significant-effect"><strong>A “Significant” Effect</strong></h4>
<p>Okay, time to bring this together. IF the null hypothesis is true, then we expect to find a slope of zero. But we also know that we may not find a slope of zero all the time because of random sampling error. So the question is - how do we know whether our non-zero slope that we found in OUR study is due to sampling error (from a population where the true slope is zero), OR is due to some REAL RELATIONSHIP between the two variables????&nbsp;</p>
<p>The answer is that statisticians made up an arbitrary threshold of 5% (or a p-value of .05). If the probability of observing your slope, relative to your estimate of sampling error, is less than 5%, then it means it is UNLIKELY that you observed this slope because of taking some random sample from a population where the slope is zero (sampling error) and MORE LIKELY that you observed this slope because you took a random sample from a population where the slope is not zero.&nbsp;</p>
<p>In other words, as a researcher looking to support your theory, you “need” to find that the p-value is small, because this is the probability that you observed your slope IF THE NULL HYPOTHESIS were “true”. When this happens, researchers say the effect is “statistically significant”.&nbsp;</p>
<p>However - we need to be careful here! A “significant effect” only means that our made-up estimate of sampling error is much smaller than the slope that we observed in our study, and that this gives us a made-up sense of confidence that we can reject the null hypothesis and say that the data supports our theory.</p>
<p>A significant effect DOES NOT mean :&nbsp;</p>
<ul>
<li><p><strong>the effect we found in our study is real.</strong> we don’t have access to the truth, and are still making a guess about what the population is like based on our limited sample. so just because an effect is significant doesn’t make it real.</p></li>
<li><p><strong>the effect we found in our study is not due to chance.</strong> there is still a chance that we are making a mistake in our estimate of sampling error. and even a small p-value of .000001 means there is a chance that we observed this slope due to random sampling error<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a>.</p></li>
<li><p><strong>the effect we found in our study is important.</strong> a “significant effect” doesn’t mean the effect is important or meaningful. That’s a question for your critical thinking brain : are these results important to society or me? How will this knowledge be used?</p></li>
<li><p><strong>the study used valid methodology.</strong> a bad study designed with poorly defined and unreliable measures, a biased sample, or an improper experimental method that is “significant” is still a bad study.&nbsp;</p></li>
</ul>
<p>So what does a significant effect mean again? A significant effect means : “We are unlikely to observe the slope we found in our sample (or one more extreme) if we were to draw a random sample from a population under conditions of the null hypothesis.”</p>
</section>
<section id="the-95-confidence-interval" class="level4">
<h4 class="anchored" data-anchor-id="the-95-confidence-interval"><strong>The 95% Confidence Interval</strong></h4>
<p>To help ensure that the reader understands the slope found in the study is not the absolute truth, but instead is an estimate that might change from sample to sample, psychologists will often report the slope that they found, along with a range of slopes based on their expected sampling error. If you’ve ever seen a political poll reporting a “margin of error”, this is an estimate of sampling error.</p>
<p>Typically, researchers report the 95% Confidence Interval - this defines 95% of the distribution of sample estimates they might expect if they were to experience sampling error around the slope that they found. The 95% confidence interval is an area around the estimate of the original slope, and is defined by the following equation.</p>
<p><span class="math display">\[
\huge \text{95% Confidence Interval} = b\pm 1.96 * SE_b
\]</span></p>
<p>Positive and Negative 1.96 are the values of the normal distribution that contain 95% of the scores<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a>. Multiplying this value by the estiamted standard error of the slope (which describes how much the slope might vary due to random sampling error) translates these boundaries into the same units as your slope. You can visualize the 95% Confidence Interval below.</p>
<p><img src="images/clipboard-4010302027.png" class="img-fluid"></p>
<p><strong>So, back to my pretend example.</strong> With a slope of .5, a standard error of .2, and a t-value of 2.5, and a p-value of 0.0132, my 95% confidence interval would be calculated as :&nbsp;</p>
<ul>
<li><p>.5 + 1.96*.2 = .892 = this is the upper limit of my estimated 95% confidence interval</p></li>
<li><p>.5 - 1.96*.2 = .108 = this is the lower limit of my estimated 95% confidence interval</p></li>
</ul>
<p>Note that a “significant effect” should show the upper and lower limits in the same direction as your original slope. So if your slope is positive, the 95% confidence interval should contain all positive numbers. If the 95% confidence interval contains zero (or a mix of positive and negative numbers) than the effect is not considered statistically significant.</p>
<p>I would then write this as : “I observed a significant and positive relationship between the DV and IV (b = .50, 95% CI = [.11, .89], t(200) = 2.5, p (two-tailed) = .0132).”&nbsp;</p>
<p>WHEW!!!</p>
</section>
</section>
<section id="calculating-nhst-in-r-very-easy" class="level3">
<h3 class="anchored" data-anchor-id="calculating-nhst-in-r-very-easy">Calculating NHST in R : Very Easy!</h3>
<p>Y’all will like this - it is very easy to do all the NHST stuff in R. First, you start with a linear model. I’m going to draw from the MBA study we’ve used before, and examine the relationship between Narcissism (NPI) and Age (age).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>mba <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"~/Dropbox/!WHY STATS/Class Datasets/hormone_data.csv"</span>, <span class="at">stringsAsFactors =</span> T)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>age.mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(NPI <span class="sc">~</span> age, <span class="at">data =</span> mba)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(NPI <span class="sc">~</span> age, <span class="at">data =</span> mba, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">xlab =</span> <span class="st">"Age"</span>, <span class="at">ylab =</span> <span class="st">"Narcissism (NPI)"</span>)</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(age.mod, <span class="at">lwd =</span> <span class="dv">5</span>, <span class="at">col =</span> <span class="st">'red'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="9R_SamplingError_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>If I look at the coefficients of the model :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(age.mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)         age 
 4.74855460 -0.05651782 </code></pre>
</div>
</div>
<p>Someone with an age of 0 is predicted to have a Narcissism score of 4.7. These data don’t make sense, since our data were only collected on adults.</p>
<p>For every year someone ages, we predict their narcissism to go down by .0565. I can see this as negative slope I drew on the graph.<br>
<br>
To do all the NHST stuff, all I need to run is the summary() function on the model that I defined; in this case I would run summary(age.mod) and get the following output :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(age.mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = NPI ~ age, data = mba)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.25302 -0.34583  0.00417  0.27644  1.41394 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  4.74855    0.61722   7.693  7.8e-12 ***
age         -0.05652    0.02217  -2.549   0.0122 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5219 on 106 degrees of freedom
  (14 observations deleted due to missingness)
Multiple R-squared:  0.05778,   Adjusted R-squared:  0.04889 
F-statistic:   6.5 on 1 and 106 DF,  p-value: 0.01222</code></pre>
</div>
</div>
<ul>
<li><p><strong>formula :</strong> hey, that’s my model!</p></li>
<li><p><strong>residuals :</strong> these describe some descriptive statistics for the residuals in my model.</p></li>
<li><p><strong>coefficients :</strong> these will report the intercept and slope, along with the NHST statistics for these terms. You can ignore the intercept for now and just focus on the columns for the slope (age) :&nbsp;</p>
<ul>
<li><p><strong>age (estimate) :</strong> = - .057 = this is the estimate of the slope for age. There’s a negative relationship between these two variables.</p></li>
<li><p><strong>std. error =</strong> .02217 = this is my estimate of the standard error (sampling error) for age. If the null hypothesis were true and the “true slope” was 0, I’d expect to find an average slope of .02 or -.02 just due to sampling error.</p></li>
<li><p><strong>t-value =</strong> -2.55 = my slope is 2.55 times larger than the standard error. I can confirm that -.057 / .02217 = 2.55. Note that when reporting the t-value, it’s also important to look up the degrees of freedom (which is the sample size - the number of things in your model.) R reports these degrees of freedom next to the residual standard error.</p></li>
<li><p><strong>p-value =</strong> 0.0122 = if the null were true, I’d expect to sample a slope of -.057 (or +.057) or more extreme about 1.22% of the time. This is a low probability and less than .05 (or 5%) so I get my little star and can say that I reject the null hypothesis - the relationship between age and narcissism is unlikely to be due to random sampling error from a null distribution.</p></li>
<li><p><strong>95% Confidence Interval :</strong> this is not calculated, but I can do a rough estimate by taking my slope (-.057) and adding and subtracting 1.96 * .02, so the 95% CI = [-0.0962, -0.0178]. Note that this range does not include zero, so it’s another way of showing the effect is significant.</p></li>
<li><p><span class="math inline">\(R^2\)</span>: hey look, it’s our good friend R2! Go ahead and focus on the “multiple R-squared” = .05778.</p></li>
</ul></li>
</ul>
<p>I would write this up as the following : “I observed a small but significant negative relationship between age and narcissism (b = -0.05, 95% CI = [-0.0962, -0.0178], R2 = .06, t(106) = -2.55, p = .01).</p>
</section>
<section id="nhst-video-explanation" class="level3">
<h3 class="anchored" data-anchor-id="nhst-video-explanation">NHST : Video Explanation</h3>
<p>For the YouTube fans.</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/ltaS5XFOdkY" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/dD1ExrzTi2s" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/cfx6EB3k63g" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
</section>
</section>
<section id="check-out-statistical-significance" class="level2">
<h2 class="anchored" data-anchor-id="check-out-statistical-significance"><a href="https://docs.google.com/forms/d/e/1FAIpQLSdnDwkovoSD1dKZysOcq_2-YyZQn1PN4SMiAeJ8Umrp4X0z2Q/viewform?usp=sf_link">Check-Out: Statistical Significance</a></h2>
<p>This shit is confusing, so here are some questions on NHST to assess your understanding. We will review answers to these in our next lecture, so save your work so we can review!!!</p>
<p>Thanks for reading! Lemme know if you have questions on Discord :)</p>
<p><img src="images/clipboard-4023328064.png" class="img-fluid"></p>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>source : <a href="https://fivethirtyeight.com/features/obamas-lead-looks-stronger-in-polls-that-include-cellphones/" class="uri">https://fivethirtyeight.com/features/obamas-lead-looks-stronger-in-polls-that-include-cellphones/</a><a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>You can <a href="https://www.dropbox.com/scl/fi/cvcwam7xe202nuocbfmbp/brainwavebabydata.csv?rlkey=5hi2xknvv83cgydurts31fvlw&amp;dl=0">access the fake dataset here</a> if you want to follow along in R, but this is not necessary and I think reading these notes should suffice.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>There are different ways that computers can take “random samples”, each with different merits. The default method R uses is ““Mersenne-Twister” From Matsumoto and Nishimura (1998). This stuff goes way beyond my pay grade; I imagine there are a few explanations on the internet. Let me know if you find a good one!</p>
<p><br>
<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Note that when I use the <code>set.seed()</code> function before the <code>sample()</code> function, I’m telling R to “fix” the random number generator it uses. This gives me a consistent result time it runs the “random” <code>sample()</code> function. And if you also run <code>set.seed(42)</code> before you run <code>sample(1:10, 1)</code> you should also get the same answer of 1. You can specify any number within <code>set.seed()</code>, and only want to use this function when you want others to get the same answer as you (like when sharing code). Most of the time, we don’t want to use this function because we want things to be “random”. Let me know if this is confusing! I can try to clarify.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>A sample size of 150 may still seem small, but it’s around the average in fields like social and personality psychology (<a href="https://journals.sagepub.com/doi/pdf/10.1177/25152459221120217">Fraley et al., 2022</a>) and well above the average in other fields like neuroscience (<a href="https://www.nature.com/articles/nrn3475">Button et al., 2013</a>).<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>&nbsp;This conceptual equation won’t give you what R calculates, because R will use something called the pooled variance in its calculation of the standard deviation (since the null hypothesis assumes no relationship between the DV and IV, it’s better to calculate a weighted average of the DV and IV for your estimate of the standard deviation. There’s a long equation to calculate this that I used to students and have them do “by hand”. However, over the years I realize that this does not help students learn, and that even the complicated equation is an oversimplification of a much more involved proof which you can learn about in more advanced classes if you want.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>&nbsp;This is called Type I error (a false positive) - when we incorrectly reject the null hypothesis. The probability of committing Type I error is defined by the p-value you set to reject the null hypothesis, typically .05 = 5%. Type II error is when you incorrectly reject the alternative hypothesis (false negative). we won’t cover how to calculate Type II error this semester (or the related concept of Statistical Power - which is an estimate of the probability you can correctly support your theory as a researcher), but they are important ideas. <a href="https://www.youtube.com/watch?v=OkbXBWuzikM">Here’s an okay video</a> that seems to give a good overview of these types of error for those students who are interested, and <a href="https://www.youtube.com/watch?v=ZIjOG8LTTh8">here’s a video walking through how to do this in R</a>. Let me know if you have questions / find better videos!<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>The exact range of the 95% confidence interval will not always be within ±1.96 standard errors of the slope - that’s the theoretical range based on a normal distribution. In practice, the range will depend on certain features of your sample and model (much like the t-distribution we discussed), but will approach 1.96 as your sample size increases; and if you want to be more conservative, you can round up to 2*SEb as long as your sample size is &gt; 30.</p>
<p><br>
<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/8R_Assumptions.html" class="pagination-link" aria-label="More Levels and Experiments">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">More Levels and Experiments</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/10R_NHSTPower.html" class="pagination-link" aria-label="Null Hypothesis Significance Testing and Power">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Null Hypothesis Significance Testing and Power</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>