# Introduction {.unnumbered}

## The Professor.
Hi again! I'm very much looking forward to the semester, and hope you are too!

Below is a short video so you can see what I look and sound like.

::: {#vid-prof}
{{< video https://youtu.be/VXxG9kxR6c0?si=vhJWQoMTMwke1d1L title = "It is me, your Professor." >}}
:::

## Goals of the Course
This class is really three classes in one semester.

1. **Statistics.** 

2. **Programming in R.** This semester, we will learn to use the free program R to work with data. No previous programming experience is required, and if it helps all the R code we will learn in this class would fit on one page

3. **Research Methods.**

## Course Structure
This semester, we'll be taking a **flipped classroom** approach to learning the statistics, research methods, and programming required of modern psychology researchers. 

1.  **Before lecture** you'll read and watch some videos to be introduced to the content that we will then cover more deeply in lecture. You'll also take a short quiz (no time limit, open-note, and you can take as many times as you'd like) that will encourage you to do the readings, and let me know what topics are still confusing to students.

2.  **During lecture** we will start with a review of concepts you learned from the pre-readings, go over any common questions that students still have, and then use the remaining time to practice and discussing the skills and concepts. We will work on the homework assignment together

3.  **After lecture** you'll complete any homework that we didn't finish in class, and then read for the next week's lecture.

The flipped classroom approach requires y'all to do the readings and watch the videos before class, and requires me to write text and record videos that are engaging and helpful for the students in the class.
