# Lab 1

Spring 2025

**Copy and paste these questions into a document (Google Doc or Word) to answer these questions.** Please number your responses to help your GSI grade. There’s no word count, and we won’t penalize students for grammar or spelling. Do your best to explain your ideas in your own words, and if you get stuck or confused, post on Discord / ask your GSI / explain why you got stuck and what you tried to do to figure things out. 

1.  **In Lecture / Chapter 2.** Define two variables in R - one numeric and one string variable (these can be unrelated to your project topic!) Make sure to collect at least ten data points for each variable, and show that you successfully defined the variable in R by "printing" it in R. Yeah, you're programming!

2.  **In Lecture.** What’s a prediction about people that you made today? What information did you use to make this prediction? How did (or could) you use this prediction to influence outcomes? Were you valid in your predictions?

3.  **In Lecture / Section / On Your Own.** Get started on the final project by thinking through a research question you might be interested in studying as a psychology researcher. (Totally fine to change this, but great to start focusing on a question.)

    -   What is your question? Why do you care about this question (and / or why does this question matter to others)? How interested in this question are you on a scale from 0 (just doing to get credit for this question) to 10 (this is what motivates you to wake up each day and you will answer this question with the energy and passion of 1000 suns)?
    -   How do your past experiences and background inform this question?
    -   What is the variable that is the focus of this question? How does this variable relate to affect, behvaior, and cognition? Which aspect of this variable are you most interested in focusing on for your project?
    -   What is the between-person form of variation for this variable? What is the within-person form of variation for this variable? **Note : for the final project, I strongly recommend focusing on a between-person variation version of the variable for the final project.**

4.  **In Discussion Section.** With your discussion section,define each of the six biases described in the Goldacre (2010) reading on cognitive biases, and come up with an example from real-life.

|                        |                |                       |
|------------------------|----------------|-----------------------|
| **Bias**               | **Definition** | **Real-Life Example** |
| Positive Evidence      |                |                       |
| Previous Belief        |                |                       |
| Patterns in Randomness |                |                       |
| Availability Bias      |                |                       |
| Social Influence       |                |                       |
| Regression to the Mean |                |                       |
